### ISSUE TITLE
Chart width not filling the canvas

### ISSUE THREAD

**Issue by Carbon401** [FVANCOP/ChartNew.js#123]
Chart width is different depending on the data and it is not scaling to fill the canvas. Here is a jsfiddle with two charts showing the problem: http://jsfiddle.net/9etwmL2a/10/

If you show several charts with different data length one below the other this results in a bad misalignment on the right side. This behaviour is not present in the Chart.js package (I've commented the original Chart.js link in the fiddle so it could be compared.

**Comment by Deemoe** [comment]
This is a great fix, I had the same issue.

Any reason why fullWidthGraph : true is not the default?  It seems like this would be the preferred behavior 99% of the time.

**Comment by FVANCOP** [comment]
Why "fullWidthGraph : true" is not a default ? Just because I'm a mathematicien and I don't like things thare are not 100 % correct. For my eyes, charts with "fullWidthGraph: true" are not 100 % correct ....
