### ISSUE TITLE
Adding lines to pie chart labels

### ISSUE THREAD

**Issue by h2hma** [FVANCOP/ChartNew.js#126]
Is there a way to add lines to the pie charts labels? because in the current solution the labels overlap if the pie section values are too small.
![graph1407912262732](https://cloud.githubusercontent.com/assets/6187728/3902093/d7f6ad8c-22b7-11e4-891c-b05e421b0ba0.png)

**Comment by FVANCOP** [comment]
This issue can be solved using the new Add-ins "shapesInChart.js".

see : Samples\shapesInChart_for_PieChart.html

![900_050_shapesinchart3](https://cloud.githubusercontent.com/assets/6121933/9589206/131d5c14-502d-11e5-8067-5db72e3310d2.png)

**Comment by FVANCOP** [comment]
Code for producing this has been improved. See : Samples\shapesInChart_for_PieChartV2.html

![canvas1](https://cloud.githubusercontent.com/assets/6121933/11045330/374313dc-8727-11e5-8819-1d2c1479e747.png)


See : https://github.com/FVANCOP/ChartNew.js/wiki/900_070_SpecialInChartData.js
