### ISSUE TITLE
Hide InGraphData on donut if %=v6%<'2%'

### ISSUE THREAD

**Issue by Billybobbonnet** [FVANCOP/ChartNew.js#129]
Hello,

I use InGraphData to display my elements labels on a donut chart as showed here: http://bit.ly/1oLS4Lh

The issue is that when a data value percent (v6 in the template variables) is bigger than 2%, the data label overlaps its neighbor.

Is there any way to hide it when v6<2?

Thanks

**Comment by ADiprashan** [comment]
how can do above method in jsp , 
Thanks
