### ISSUE TITLE
Chart Highlighting

### ISSUE THREAD

**Issue by Strainy** [FVANCOP/ChartNew.js#16]
So this project is awesome. It solves a lot of the issues I've encountered with the original Chart.js library.

Just a feature request here, but I think it would be great to have an option to highlight chart segments on hover. I'm not sure how difficult this would be to implement, but it would make charts feel a lot less static.

**Comment by ahmadalyan** [comment]
is there any news about this feature or it isn't in the development schedule

**Comment by FVANCOP** [comment]
Not yet planned, but I have an idea on how to implement it; Not sure that it will work, but I will try in the coming month (I hope I can implement it before May)

**Comment by budlink** [comment]
I am just leaving a wish for this feature too!  Great job on all that was added!

**Comment by FVANCOP** [comment]
highLight option has been added in ChartNew.js

Set option highLight to true : when the mouse is hover a piece of chart, this piece is highLighted.


Samples : 
     http://fvancop.github.io/ChartNew.js/Samples/highLight2.html
     http://fvancop.github.io/ChartNew.js/Samples/highLight2.html

Documentation:
     https://github.com/FVANCOP/ChartNew.js/wiki/100_25_highLight
