### ISSUE TITLE
title overlap in pie chart

### ISSUE THREAD

**Issue by nhaemu** [FVANCOP/ChartNew.js#165]
If there is no data in a given title, the title are overlap. How can I solve it?

**Comment by baj84** [comment]
Hey, I can't seem to fix this problem with your above solution. Please see the attached image
![ss](https://cloud.githubusercontent.com/assets/2744292/6105744/810b9a72-b052-11e4-8260-81fe771737a1.jpg)

**Comment by FVANCOP** [comment]
Hi @baj84 ,

This is a not an easy problem....Small slices will always be a problem. But, some ideas for solving it : 

In the sample folder, I have created a new entry :  inPieData.html. In this sample, 4 solutions are proposed; I think that the first one is the least bad solution (the values of the constants minAngle and offSet need to be adjusted to your case).

Solution 1 and 2 are based on option-functions (https://github.com/FVANCOP/ChartNew.js/wiki/130_option_functions).

Solution 3 is based on array values for an option (https://github.com/FVANCOP/ChartNew.js/wiki/085_option_array_func).

Solution 4 is a sample of option inGraphDataMinimumAngle.

I hope that it will help you to find an acceptable solution.

**Comment by thaparmonika** [comment]
inGraphDataMinimumAngle really works for me.

Set option inGraphDataMinimumAngle to a value greater than 0

Thanks
Monika
