### ISSUE TITLE
IE8 explorercanvas patch not working

### ISSUE THREAD

**Issue by alabels9** [FVANCOP/ChartNew.js#182]
Hi there,
I switched over to ChartNew.js from Chart.js, but the explorer canvas patch for IE8 is not working.
I've included it as suggested in the conditional comment, and it used to work with Chart.js but won't work with ChartNew.

I've read and tried the options from https://code.google.com/p/explorercanvas/wiki/Instructions

Has anyone else had issues or figured it out?

**Comment by ASH-khan** [comment]
IE8 attachEvent Error issue still there.
i am using latest version and having the same issue.
thanks

**Comment by FVANCOP** [comment]
Last version of ChartNew.js was not working on IE8. Problem fixed (but not related to attachEvent).

@ASH-khan : Can you test it and if problem remains can you send your code to my email address ?
