### ISSUE TITLE
Annotation appearing behind canvas when multiple canvases exist on page

### ISSUE THREAD

**Issue by nemmons** [FVANCOP/ChartNew.js#184]
Hello. I have a page with three different canvases. The chart annotations only work correctly on the first one... For a while i thought that the annotations weren't working at all on the the second two, and then i realized that I think they are - they're just displaying behind the canvas rather than in front of it:

![image](https://cloud.githubusercontent.com/assets/924353/5075010/a09d5038-6e5d-11e4-90d6-1af602e36b8f.png)

The only options that i'm using for annotations are:
"annotateDisplay : true,
annotateLabel : "<%=v1 + ': ' + v3%>"

If there is any other information that I can provide to help diagnose this issue, please let me know. Thanks again for your work on this incredible library!

**Comment by Doha83** [comment]
Interestingly enough, I have also just encountered this problem.

@FVANCOP I will see if I can get an example knocked up for demonstration. Whilst not an ideal solution, I found that increasing the z-index of the 'divCursor' element (the annotation div) it will eventually display the annotation (have not worked out why this is the case yet, investigating).

**Comment by mbormeth** [comment]
<style>
	#divCursor {
		z-index: 100;
	}
</style>

Fixed it for me :)

**Comment by FVANCOP** [comment]
Can you check if problem is solved with last version (zIndex=999 added for annotateDIV) ?
