### ISSUE TITLE
Y-axis upper value incorrect if upper/lower values are the same

### ISSUE THREAD

**Issue by Burkazoid** [FVANCOP/ChartNew.js#200]
If I create a line graph with two values the same (in the case below, value 1 and 2 are both 67), the upper Y-axis value seems to be incorrect. In the graph below, I have `yAxisMinimumInterval` set to 100. You can see that the y-axis unnecessarily climbs to 200, rather than 100.

![clipboard01](https://cloud.githubusercontent.com/assets/1105014/5359119/da7e2230-7fb2-11e4-84c0-6660780afd4d.png)

This appears to be caused by this code at line 2030:

``` javascript
            if (Math.abs(upperValue - lowerValue) < 0.00000001) {
                upperValue = Max([upperValue * 2, 1]);
                lowerValue = 0;
            }
```

In my case, `upperValue` and `lowerValue` are both 67 at when it reaches this line, so `upperValue` is then set to 134 instead and `lowerValue` (correctly) to 0.

This can be reproduced on http://charts.livegap.com/ :

![clipboard02](https://cloud.githubusercontent.com/assets/1105014/5359259/d79768fa-7fb3-11e4-9a03-0fb59ec363fb.png)

I can override the value by setting `graphMax` to 100, which does fix it, but I just thought I'd let you know.

**Comment by HaoyunS** [comment]
<code>graphMax</code> seems to work fine with "100"s, but when set to 1500, the max Y label is still 2000.

**Comment by FVANCOP** [comment]
Hi @HaoyunS   ! 

Thanks for reporting this problem - The algorithm has been a little bit changed to achieve a better result. I'm sure it is not perfect. I think that the function calculateScale has to be rewritten but it is not easy to find out what is the best solution. Can you check if the new version is closer to what you expect  ?

Francois

**Comment by HaoyunS** [comment]
Yes, it works much better now.
Thank you so much for the quick fix!

On Mon, Feb 9, 2015 at 4:28 PM, Francois Vancoppenolle <
notifications@github.com> wrote:

> Hi @HaoyunS <https://github.com/HaoyunS> !
>
> Thanks for reporting this problem - The algorithm has been a little bit
> changed to achieve a better result. I'm sure it is not perfect. I think
> that the function calculateScale has to be rewritten but it is not easy to
> find out what is the best solution. Can you check if the new version is
> closer to what you expect ?
>
> Francois
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FVANCOP/ChartNew.js/issues/200#issuecomment-73593795>.
>



-- 

Haoyun Su
LinkedIn <https://www.linkedin.com/in/haoyunsu> | haoyunsu.com
[image: Haoyun Su on about.me]
