### ISSUE TITLE
Line Chart Show Annotate when 'near' the point and not only on mouse hover?  

### ISSUE THREAD

**Issue by markudevelop** [FVANCOP/ChartNew.js#211]
Hello,

Great job on continuing developing the ChartJS package this looks awesome, I have noticed that after `annotateDisplay : true` activating tooltips, In my line chart I have to mouse over the point to see the tooltip but original you had only to come close to it to pop I absolutly hate that you need to point your mouse 100% on the point, And I really want to change this, I didn't see any `annotate` options for  this one is it possible?

**Comment by saurabh-patil** [comment]
@FVANCOP all these attributes not working on my side, I tried with all possible solution of yours but still my annotations are showing while I hover some points away from points.

**Comment by FVANCOP** [comment]
Can you send your code to my email address (you will find it in the code of ChartNew.js)

**Comment by saurabh-patil** [comment]
Hi FVANCOP,

Attached is the file containing chartNew JS code with the chart options.


On Wed, Apr 1, 2015 at 1:55 AM, Francois Vancoppenolle <
notifications@github.com> wrote:

> Can you send your code to my email address (you will find it in the code
> of ChartNew.js)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FVANCOP/ChartNew.js/issues/211#issuecomment-88233466>.
>



-- 
Regards,

*Saurabh Patil*
*saurabh_patil@tudip.com <saurabh_patil@tudip.com>** | **Skype:
saurabhpatil.tudip*
*www.tudip.blogspot.com <http://www.tudip.blogspot.com>** |
**www.facebook.com/tudiptechnologies
<http://www.facebook.com/tudiptechnologies> *
*+91 20 4674 0881 | +1 408 216 8162*


<http://steersimple.com/wp-content/uploads/2012/07/SteerSimpleLogofinal.png>
|  <http://www.steersimple.com>

**Comment by vqanguyen** [comment]
Hi FVANCOP, i have the same issus. When i set `	  responsive : true,  maintainAspectRatio : true,`  When i move mouse outside or inside the Bar/StackedBar, the detection is not correct. It's normal or not ?? How can i overcome this issus ? Thanks you.

**Comment by FVANCOP** [comment]
Hi,

I cannot reproduce your problem; Can you take contact with me by mail (to avoid lot of messages for all people interested in this project).

In your mail, you have to provide : 
-  your sources,
- the OS where it has been tested, the browser and the version of the browser.

Regards,
François

**Comment by FVANCOP** [comment]
Problem solved : canvas specifications (width/height/max-width) are defined through a CSS file; removing those definitions solved the problem.
