### ISSUE TITLE
Responsive issue will not re render to original size, Always increase in size.

### ISSUE THREAD

**Issue by voidale** [FVANCOP/ChartNew.js#213]
Okay here is how I face this issue:
When I resize the browser window and restore to full window the chart will increase in size the more you resize the more the increase in size. 

(responsive: true, maintainAspectRatio: false) Basically it looks like it will resize to become bigger but not resize down to become smaller
Here are 2 photos: 
1. first visit normal chart size
http://s8.postimg.org/lrnsoeox0/First_View_Normal.jpg
2. after resizing and restoring the window few times
http://s8.postimg.org/ykbwoc0is/Afte_Resizing.jpg

I'm using bootstrap panel and found ChartJs pull which possibly offer the fix for this?
https://github.com/nnnick/Chart.js/pull/722

**Comment by tzachar** [comment]
Hi.

I have the same exact problem.
Solved it with the following hack:

1) set responsive: false
2) add the following cb on window load and resize:
     $(".graph_container_cls").each(function(i,el){
                $(el).attr({
                    "width":$(el).parent().width(),
                    "height":$(el).parent().outerHeight()
                });
            });
       redraw_graphs();

seems to work for me.

**Comment by ssarnecki** [comment]
It doesn't work for me. The legend is gone after update don't know why.

**Comment by FVANCOP** [comment]
@ssarnecki  :   this problem is not related to issue #213 ; Can you open another issue for it or  send the code that you use (you can send it to my email address).

Regards,
François

**Comment by FVANCOP** [comment]
Problem seems to be fixed.

see #331 , #309
