### ISSUE TITLE
Long labels in chart data.

### ISSUE THREAD

**Issue by mbormeth** [FVANCOP/ChartNew.js#219]
Hey m8. :) 
I noticed if the label is long enough it pushes the whole chart or even refuses to render it.
Do you have any work-around for this? 
Maybe limit displayed characters and show on hover?

**Comment by FVANCOP** [comment]
Can you give a sample ?

**Comment by mbormeth** [comment]
var mydata1 = {
	labels : ["Forbik\u00f8rsel af punkt uden k\u00f8rtilladelse, med et andet k\u00f8ret\u00f8j end et tog, i omr\u00e5de uden centralsikring","February","March","April","May","June","July"],
	datasets : [
		{
			fillColor : "rgba(220,220,220,0.5)",
			strokeColor : "rgba(220,220,220,1)",
			pointColor : "rgba(220,220,220,1)",
			pointStrokeColor : "#fff",
			data : [0.65,0.59,0.90,0.81,0.56,0.55,0.40],
      title : "pFirst data"
		},
		{
			fillColor : "rgba(151,187,205,0.5)",
			strokeColor : "rgba(151,187,205,1)",
			pointColor : "rgba(151,187,205,1)",
			pointStrokeColor : "#fff",
			data : [0.28,0.48,0.40,0.19,0.96,0.27,1.00],
      title : "pSecond data"
		}
	]
}


Like this taken from the sample.html :) Due to the long label some of the charts refuse to render,

**Comment by FVANCOP** [comment]
Indeed, with such wide labels, it has no space to draw the chart even if it rotates the labels. Thats why the chart is not displayed (some computed values are negative and therefore, the graph can not be displayed).

Solution 1 : increase the width of the canvas (at least 5500 pixels for you sample); But, then, the chart can not be displayed on a normal screen and that is not really the purpose of a chart...

Solution 2 : put the labels on more than one lines with "\n"

"Forbik\u00f8rsel af punkt uden\nk\u00f8rtilladelse, med et andet\nk\u00f8ret\u00f8j end et tog,\ni omr\u00e5de uden centralsikring"
 
If the first label is long, you will have also to force space on the left with option "spaceLeft"  (ex: spaceLeft : 100) and/or with a forced rotation of the labels (ex : rotateLabels: 90).

This is the line chart from "sample.html" obtained with option spaceLeft:100 

![widelabel](https://cloud.githubusercontent.com/assets/6121933/5710960/0802d1f6-9aa7-11e4-839a-cf09e4bc6ca2.png)

Hope it helps.

**Comment by mbormeth** [comment]
@FVANCOP Thx for the quick solutions. :) I will try to incorporate the 2nd solution.
