### ISSUE TITLE
Null data values get displayed as zero

### ISSUE THREAD

**Issue by kroche** [FVANCOP/ChartNew.js#222]
I have an issue where null values in the data are present and should actually be skipped over rather than displayed as zero. On a line chart it should just miss out that point so that the line is drawn from the previous point to the next one. On a Bar chart the Bar at a null point should not be displayed.

Is there a parameter I can set to achieve that?

**Comment by kroche** [comment]
I have solved this by changing the data from: 
"data":[3.0,2.1,3.7,4.1,4.0,3.0,null,null],
to
"data":[3.0,2.1,3.7,4.1,4.0,3.0, , ],

**Comment by FVANCOP** [comment]
It is even better to specify 'undefined' (without the quote)  :


data:[3.0,2.1,3.7,4.1,4.0,3.0, undefined, undefined ],  

"null" is not considered as a missing value... but as a variable with name null....

see also : https://github.com/FVANCOP/ChartNew.js/issues/75
