### ISSUE TITLE
Label interval

### ISSUE THREAD

**Issue by niekproductions** [FVANCOP/ChartNew.js#223]
Hi,
I love your library and I'm using it for [my thermostat](https://github.com/NiekProductions/WTherm/). However, when I make a chart with a lot of data points, they're bunched up together like this: http://i.imgur.com/HtPrnOM.png. Is there an option in ChartNew to set an interval for these x-Axis labels? Like to only show every second, fourth..

**Comment by FVANCOP** [comment]
Thanks for using ChartNew.js !

There is a sample in the sample folder "Samples/time_graph.html". You have to work with xPos ; see https://github.com/FVANCOP/ChartNew.js/wiki/070_010_Line - section "Line with points not associated to the labels".

**Comment by niekproductions** [comment]
Thanks!
