### ISSUE TITLE
Array Bar Colors

### ISSUE THREAD

**Issue by nickmccally** [FVANCOP/ChartNew.js#225]
The colors array, which formally allowed you to put an array of colors for a bar graph is no longer working. Documentation still shows it as a feature.

**Comment by nickmccally** [comment]
I've reverted to the prior version which is working. However, the function to change colors  based on value of the dataset is not working with that version.

**Comment by FVANCOP** [comment]
Hi Nick,

Thanks for reporting the bug. It has been fixed. Please download the last version to get the fix.

In previous version, the parameter have to be called differently. This part has been rewritten in version 2 with new parameters. See issue #221.

Francois

Can you close the issue if it is ok for you ?

**Comment by nickmccally** [comment]
Thank you so much for the quick response and fix! It is now working exactly as I anticipated
