### ISSUE TITLE
Is it possible to add pie chart border like this?

### ISSUE THREAD

**Issue by baj84** [FVANCOP/ChartNew.js#227]
Hi, 
![ss](https://cloud.githubusercontent.com/assets/2744292/5918239/56dd66d8-a61e-11e4-8b46-a586e01dda1a.jpg)

I'm trying to get this border around the pie chart and the different positions of the v1 and v2 variables - Is this possible, if so could you please point me in the right direction?

Thanks!

**Comment by FVANCOP** [comment]
Hi,

Unfortunately, none of your requests are possible with current version. But, I think that is will be in a future version...I will put it in the todo list. In fact, it should be nice if with Pie chart you could display  doughnut(s) around the Pie (with other data) - For your request, the doughnut should have the same data... 

François

**Comment by baj84** [comment]
Perfect, thanks a lot.

On 27 January 2015 at 14:58, Francois Vancoppenolle <
notifications@github.com> wrote:

> Hi,
>
> Unfortunately, none of your requests are possible with current version.
> But, I think that is will be in a future version...I will put it in the
> todo list. In fact, it should be nice if with Pie chart you could display
> doughnut(s) around the Pie (with other data) - For your request, the
> doughnut should have the same data...
>
> François
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FVANCOP/ChartNew.js/issues/227#issuecomment-71660878>.
>



-- 




*Ben Southall*
*w:* www.bsouthall.com
*m: 0777 5122 647*

**Comment by omarsedki** [comment]
You can use Simulate it with gradient Colors

ex:
 {value :65,
color:parent.gradientColor,gradientColors :["rgba(52,152,219,1) 1%","rgba(52,152,219,1) 80%","#004d80 81%",],title:'January'},


![canvas](https://cloud.githubusercontent.com/assets/8490104/5937126/fdf9711c-a6fc-11e4-87e7-7c01c8c8e3d3.png)
![canvas2](https://cloud.githubusercontent.com/assets/8490104/5937128/0371f3d0-a6fd-11e4-88bc-f5324631c48e.png)
i am  now adding an option on my Online Chart generator (http://charts.livegap.com) for chartnew.js to simulate this
open  colors --> color Scheme--> Color Style
