### ISSUE TITLE
scaleShowHorizontalLines

### ISSUE THREAD

**Issue by AngryJust** [FVANCOP/ChartNew.js#231]
HI!
Is it possible to hide only horizontal (or vertical) grid line in horisontal bar chart? scaleShowGridLines:false hide both of them. 
Thanks! 
![image](https://cloud.githubusercontent.com/assets/3660863/5973563/0bcb1848-a87b-11e4-95f2-57edeac192eb.png)

**Comment by FVANCOP** [comment]
Yes ! 

scaleYGridLinesStep : 9999

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#scaleygridlinesstep  and https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#scalexgridlinesstep

**Comment by AngryJust** [comment]
Thx for your answer, its work, but not correctly! First horisontal line is still here (look at image)
![image](https://cloud.githubusercontent.com/assets/3660863/5999341/082d1efc-aae2-11e4-870d-89517fee9d28.png)

**Comment by FVANCOP** [comment]
Oups - not sufficiently tested... Download the last version; the problem has been fixed.

**Comment by AngryJust** [comment]
Hi! I tried again now, but the line is still here

**Comment by FVANCOP** [comment]
Are you sure that you use the last version ?

My test is correct with the last version.

![canvas](https://cloud.githubusercontent.com/assets/6121933/6604963/a3b340f6-c82c-11e4-93af-10cf126eb5c8.png)
