### ISSUE TITLE
StackedBar much empty overhead

### ISSUE THREAD

**Issue by Bjolja** [FVANCOP/ChartNew.js#233]
When using stackedbar with the highest value 111, it chooses 200 as max X value making almost half of the drawing area empty. This feels like waste of space.

Below are my settings:
{
        animation: false,
        annotateDisplay: true,
        scaleStartValue: 0,
        graphTitle: container.attr("data-title"),
        barShowStroke: true,
        showTooltips: true,
        yAxisMinimumInterval: 1,
        tooltipEvents: ["mousemove", "touchstart", "touchmove"],
        maintainAspectRatio: true,
        responsive: true,
        legend: true,
        annotateLabel: "<%= v1 + ' ' + v2 + ': ' + v3%>"
    }

**Comment by FVANCOP** [comment]
The top and bottom values are computed to "round" values (in your sample, 200 and not 125). But, I agree that sometimes, it is not what people want.

I have extended the option graphMaximized to line, bar, stackedBar, stackedBar and horizontalStackedBar (previously, the option was only valid for radar chart). In your case, set option graphMaximized : "top" (you can also set it to true, but in that case, the minimum value will not be 0 in some cases). 

You have to download the new version published 5 minutes ago.

See : https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmaximized

**Comment by Bjolja** [comment]
Wow thanks. This was exacly what i needed.
