### ISSUE TITLE
Please add feathure for ShowXlabels

### ISSUE THREAD

**Issue by dheerajswami123** [FVANCOP/ChartNew.js#236]
Hi,

In ChartJS, new encahcement is added for show how many x-axis lables. Like there are 1000 dates and we want to show only 20 and based on that data should be shown.

Please add this feature of : showXLabels, which is already developed into Chartjs.

**Comment by AK1979** [comment]
++

**Comment by FVANCOP** [comment]
option showXLabels and showYLabels are already implemented.

https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#showxlabels
https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#showylabels
