### ISSUE TITLE
With Latest Build After passing color Array Line are of same color while legend shows color different

### ISSUE THREAD

**Issue by dheerajswami123** [FVANCOP/ChartNew.js#237]
With Latest Build After passing color Array Line are of same color while legend shows color different

**Comment by FVANCOP** [comment]
Sorry, I don not understand what you mean; Can you please insert a sample (code + graph) ?

Thanks,
François

**Comment by dheerajswami123** [comment]
With New code if you pass array of colors, legend shows different color but all lines of graph are of same color.

That means legend is accepting array of colors but graph is rendering all series of first color only.

**Comment by FVANCOP** [comment]
@dheerajswami123

Can you please give more information :

What type of chart : line, bar, horizontalBar, ...
To which option/variable did you assign an array of color ?

Eventually put the code (or send it to my mail address) and/or drag a (saved as png) chart in the issue.

Thanks,
François
