### ISSUE TITLE
Is is possible to show Annotation for one line (or bar) of a graph but not to second

### ISSUE THREAD

**Issue by dheerajswami123** [FVANCOP/ChartNew.js#243]
Hi,

I have a graph in which i want to show data and tool-tip for one series but do not want to show for second one.

How i can achieve this.

**Comment by FVANCOP** [comment]
Creates following (similar) function : 

function setAnnotate(area,ctx,data,statData,posi,posj,othervars)
{
  if(posi==0)return(true);
  else return(false);
}

and associates the function to the variable annotateDisplay -  annotateDisplay : setAnnotate

**Comment by dheerajswami123** [comment]
Hi,

Thanks you but i have bar and line chart (combined) and i do not want to show annotation as well tooltip for bar chart while want to show annotation and tooltip for all line chart. So how could i know for which type of graph its rendering.

**Comment by FVANCOP** [comment]
Yes, it is possible; Instead of using the setAnnotate function, create the here defined "isLine" function.

I suppose that, with "tooltip", you mean "inGraphDataShow". 

function isLine(area,ctx,data,statData,posi,posj,othervars)
{
	if(ctx.tpchart=="Bar") {
		if(typeof data.datasets[posi].type == undefined || data.datasets[posi].type=="Line") return(true);
		else return(false); 
	} else if (ctx.tpchart=="Line") {
		return(true);
	}
	else return(false);
	
}

And define options like this :  
      inGraphDataShow : isLine
      annotateDisplay : isLine
