### ISSUE TITLE
Pie Chart annotateLabel function

### ISSUE THREAD

**Issue by Sanprof** [FVANCOP/ChartNew.js#248]
Hi, I tried to apply function to annotateLabel option, function is called, but posi always 'undefined' and posj always '-1', I need apply a custom label for each object in dataset knowing only index. Here is my function.

var anotateLableFunc = function (area, ctx, data, statData, posi, posj, othervars) {
                var label = '';
                if (posi == 0) {
                    label = 'Boni/Mali';
                } else if (posi == 1) {
                    label = 'Performance';
                }
                return "<%= '" + label + ": ' + v2 %>";
            }

Maybe I'm doing something wrong.

**Comment by FVANCOP** [comment]
You are 100 % correct; It is a bug; Download the last version; It has been fixed !

Thanks for reporting the problem.
François

**Comment by Sanprof** [comment]
Ok, now it is working as I need, thank you for this fix.
