### ISSUE TITLE
Chart not expanding to the total width

### ISSUE THREAD

**Issue by M4tho** [FVANCOP/ChartNew.js#249]
Hi,
When u have a lot of values the chart doesnt use the entire width of the canvas

I've recreated the problem in a JSFiddle:
http://jsfiddle.net/k311a7c1/

This does not occur in the normal version of ChartJS

**Comment by FVANCOP** [comment]
see issue #123 and #78. You have to set option "fullWidthGraph : true"

**Comment by M4tho** [comment]
That fixed the problem.
Thanks for the quick response
