### ISSUE TITLE
Please publish ChartNew.js as an NPM module

### ISSUE THREAD

**Issue by bogdanvalsan** [FVANCOP/ChartNew.js#251]
Hi Guys,

It would be great if you could publish ChartNew.js as an NPM module, making life so much easier for some developers. This will allow developers using browserify or webpack to package up client side libraries fetched with npm.
And it only takes just a few minutes to publish a npm module.

Thanks.

**Comment by jewelsjacobs** [comment]
+1

**Comment by FVANCOP** [comment]
No problem to do it but .... just explain what I have to do :-)

**Comment by vinimxit** [comment]
Any update on this?

**Comment by FVANCOP** [comment]
As soon as someone explain what I have to do to plusish it as a NPM module, I will do it... But if nobody explains me what I have to do, the situation will not change ....

**Comment by vinimxit** [comment]
Have a look at this link. https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by FVANCOP** [comment]
I think that is done. Can you check if it is what you want ?

npm install chartnew.js

**Comment by ChrisMashie** [comment]
Hey would it be possible to update the npm package for the new version 3?

**Comment by FVANCOP** [comment]
File package.json updated. Is this suffisient ? Otherwise, can you explain what I have to do...

**Comment by JoshuaCWebDeveloper** [comment]
@FVANCOP After updating the package.json version, run `npm publish` again.
https://docs.npmjs.com/getting-started/publishing-npm-packages
Thanks!

**Comment by FVANCOP** [comment]
"npm publish" command executed. Sorry for the long delay...

Result of the command : 
>npm publish
+ chartnew.js@3.9.0

Can someone confirm that the last version is available ?

**Comment by markosko** [comment]
https://www.npmjs.com/package/chartnew.js Yeah, v3.9 is published ;)
