### ISSUE TITLE
in line chart if there is single value it should show dot. 

### ISSUE THREAD

**Issue by bhavyamanasa** [FVANCOP/ChartNew.js#254]
i have a line chart which shows value according to the months. if i select more then one month it is showing line. If i select only one month, then it should show me dot and value. but it is not showing dot and value for single month. 
for single month my graph looks like

![pic9](https://cloud.githubusercontent.com/assets/11133804/6485755/ee0c5e52-c2ab-11e4-9552-744e4a08fb71.png) 

for multiple months my graph looks like

![pic10](https://cloud.githubusercontent.com/assets/11133804/6499466/9556ad32-c321-11e4-922d-3ec4101c510e.png)

**Comment by FVANCOP** [comment]
Thanks for reporting the problem; It has been fixed (download the last version). 

François

**Comment by bhavyamanasa** [comment]
its working.. thanku :)
