### ISSUE TITLE
Bar color dynamically

### ISSUE THREAD

**Issue by dheerajswami123** [FVANCOP/ChartNew.js#256]
Hi,

After defining data to bar chart for single series can i assign different colors to each bar i.e. i have one bar chart but i want to assign colors of each bar while rendering.

Thanks
Dheeraj

**Comment by FVANCOP** [comment]
See following issue : https://github.com/FVANCOP/ChartNew.js/issues/28

See also wiki : https://github.com/FVANCOP/ChartNew.js/wiki/070_020_Bar
