### ISSUE TITLE
Legend order in PolarArea

### ISSUE THREAD

**Issue by tzachar** [FVANCOP/ChartNew.js#257]
Hi.

Why is the legend order in PolarArea reversed?
Can an option to explicitly specify reversed or not be added?
This generates weird graphs where the legend's order does not match the data order

![image](https://cloud.githubusercontent.com/assets/4946827/6570344/95cc8a8c-c701-11e4-8965-38186dd46157.png)

**Comment by FVANCOP** [comment]
It seems logical to start the legend at the right. But, I agree that when you have only 2 slices, it is a little bit strange. To avoid this, set option startAngle : 270 ; 


![polar](https://cloud.githubusercontent.com/assets/6121933/6580934/ff9d497c-c753-11e4-9736-2bcff4b8af2b.png)
