### ISSUE TITLE
Set yAxis MaxValue

### ISSUE THREAD

**Issue by Sanprof** [FVANCOP/ChartNew.js#258]
Hi,

I can't find an option to set yAxis max value. If line chart has all dot with the same value (first image), I need that yAxis always display not more than max value, in my case it is 100. See attached.

![image1](https://cloud.githubusercontent.com/assets/8988717/6599404/435d6aca-c812-11e4-8931-6f1231fdbba3.png)
![image2](https://cloud.githubusercontent.com/assets/8988717/6599407/47bd0454-c812-11e4-956e-b3958ca51110.png)
![image3](https://cloud.githubusercontent.com/assets/8988717/6599409/4ab11470-c812-11e4-959f-cdd77d3bbb2b.png)

**Comment by FVANCOP** [comment]
use options graphMax and graphMin.

graphMax : 100

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmax

**Comment by Sanprof** [comment]
Thanks you very much for your reply, I mistakenly applied this option for other type of chart and thought that this option does not work, but now I have applied it correctly and all working fine, thanks.
