### ISSUE TITLE
Letting bars for barlineChart begin on 0 when their axis starts at a negative number

### ISSUE THREAD

**Issue by blagae** [FVANCOP/ChartNew.js#260]
Can we configure a chart with multiple axes to have bars from one side begin on 0, even if the axis itself begins on a negative number ?

The use case is for climate graphs, where temperature can fall below zero, but of course rainfall cannot. For clarity, both scales must have their 0 point at the same height.

Example (PNG): http://www.meteo.be/gfx/climatograms/nl4250.png

**Comment by FVANCOP** [comment]
Try this : 

     var mydata1 = {
	labels : ["January","February","March","April","May","June","July"],
	datasets : [
		{
			fillColor : "rgba(220,220,220,0.5)",
			strokeColor : "red",
			pointColor : "rgba(220,220,220,1)",
			pointstrokeColor : "yellow",
			type : "Line",
			axis : 2,
			data : [-8,-1,14,20,18,24],
		      	title : "Temperatuur"
		},
		{
			fillColor : "rgba(151,187,205,0.5)",
			strokeColor : "rgba(151,187,205,1)",
			pointColor : "green",
			pointstrokeColor : "yellow",
			data : [35,43,59,,31,50,66],
      			axis : 1,
      			title : "Neerslag"
		}
	]
     }               


     var opt1 = {
      legend : true,
      graphMin : -20,
      graphMax : 90,
      graphMin2 : -10,
      graphMax2 : 45,
      yAxisLabel : "Neerslag",
      yAxisLabel2 : "Temperatuur",
      yAxisRight : true
     }


![canvas](https://cloud.githubusercontent.com/assets/6121933/6643375/fafa8e3e-c9ab-11e4-873c-3fde95277d03.png)

Documentation : 

https://github.com/FVANCOP/ChartNew.js/wiki/100_035_DoubleAxis
https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmax
https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmin

I think that the only difference is that the 0 are not on the same place for both axis.

Regards,
François

**Comment by blagae** [comment]
Wow, thanks. I was trying to do this manually with overrideAxis options, but that lost the property I wanted.
