### ISSUE TITLE
inGraphData confused and color

### ISSUE THREAD

**Issue by larsurilch** [FVANCOP/ChartNew.js#261]
Hello Francois,

Is there a parameter that let the text more readable when there are very similar values ​​? Another question , how can the labels in the same graph color?

![graph](https://cloud.githubusercontent.com/assets/251246/6660284/cbe5bff4-cb74-11e4-9260-445e37156d70.png)

Thanks

**Comment by FVANCOP** [comment]
It is possible but not through parameters; You have to define functions associated to some options.

See : https://github.com/FVANCOP/ChartNew.js/wiki/085_option_array_func

For your problem, a solution could be the following (please download the last version - I made a small change for option legendFontColor) : 


Define the following functions in your code : 

     var setInGraphColor = function (area, ctx, data, statData, posi, posj, othervars) {
	     if(posi==0)return("blue");
	     else return("red");
     }
     var setPosInGraphData = function (area, ctx, data, statData, posi, posj, othervars) {
	     otherline=1*(posi==0);
	     if(Math.abs(data.datasets[posi].data[posj]-data.datasets[otherline].data[posj]) < 5) {
		     if(data.datasets[posi].data[posj]<data.datasets[otherline].data[posj] || (posi<otherline && data.datasets[posi].data[posj]==data.datasets[otherline].data[posj])) {
			     if (area=="INGRAPHDATAVALIGN") return("top");
			     if (area=="INGRAPHDATAPADDINGY")  return(-6);			
		     } else {
			     if (area=="INGRAPHDATAVALIGN") return("bottom");
			     if (area=="INGRAPHDATAPADDINGY")  return(6);			
		     }
	     } else {
		     if (area=="INGRAPHDATAVALIGN") return("bottom");
		     if (area=="INGRAPHDATAPADDINGY")  return(3);			
	     }
     }

and set following options : 

      inGraphDataFontColor : setInGraphColor
      legendFontColor : setInGraphColor
      inGraphDataVAlign : setPosInGraphData
      inGraphDataPaddingY: setPosInGraphData

You will find a sample in "Samples\issue_261.html".

![canvas](https://cloud.githubusercontent.com/assets/6121933/6677507/0d7d01fe-cc31-11e4-91f9-47943f88c3bc.png)

**Comment by larsurilch** [comment]
Hello Francois,

It was exactly what I needed .

Thank you very much.
