### ISSUE TITLE
reverseOrder switch in HorizontalBar reverses bars but not values

### ISSUE THREAD

**Issue by bobsabio** [FVANCOP/ChartNew.js#263]
The reverseOrder switch currently correctly reverses the display order of bars in a HorizontalBar graph but doesn't reverse the displayed data values. In the following screenshot, I'm displaying the issue_130.html sample which showcases the feature. However, as you can see, the text values are in reverse and do not match the bar values.

![reverseorder](https://cloud.githubusercontent.com/assets/11628413/6799363/1c9917e0-d20d-11e4-906e-6e06e5fa9a48.png)

**Comment by FVANCOP** [comment]
Thanks for reporting the problem. It has been fixed (download the last version).

**Comment by bobsabio** [comment]
Amazing. Thanks very much! I wasn't expecting such a quick fix.
