### ISSUE TITLE
Different annotateLabel for second set of data?

### ISSUE THREAD

**Issue by chromacha** [FVANCOP/ChartNew.js#272]
Hi, this is such a powerful fork to Chart.js - I'm working on a multi y-axis graph with different units, one is in $ and the other a number. Is it possible to have a different annotateLabel for the second y axis? e.g. like annotateLabel2 or something? FYI this is the option setting atm:
<pre>
	responsive : true,
	  yAxisRight : true,
	  scaleOverride: true,
	  scaleSteps: 10,
	  scaleStepWidth: 2000000,
	  scaleStartValue: 0,
	  scaleOverride2: true,
	  scaleSteps2: 5,
	  scaleStepWidth2: 2000,
	  scaleStartValue2: 0,
	  yAxisLabel : "Amount ($)",
	  yAxisLabel2 : "Number of incidents",
	  annotateDisplay : true,
	  annotateLabel : '<%=v2%> - <%=v1%>: <%=v3%>',
	  scaleLabel : '$<%=value/1000000%>M',
	  scaleLabel2 : '<%=value/1000%>K',
	  thousandSeparator : " ",
	  fmtYLabel: "notformatted",
	  fmtYLabel2: "notformatted",
</pre>
Thanks!

**Comment by FVANCOP** [comment]
Hi, it is not necessary to define a new option for it. You can use 'v11' to test the line for which the annotation is for. https://github.com/FVANCOP/ChartNew.js/wiki/120_Template_variables


Solution 1 : 

      annotateLabel : "<%=( (v11==0) ? v3+' Km' : v3+' Miles') %>",


Solution 2 : 

      annotateLabel : "<%= myFunction(v11,v3) %>",


     function myFunction(line,value) {
       if(line==0) return(value+" Km"); 
       else return(value+" Miles");
     }

**Comment by chromacha** [comment]
Thank you soo much! That work perfectly :)
