### ISSUE TITLE
How to use abbreviated numbers for inGraphData (ex: 12345 -> 12k)

### ISSUE THREAD

**Issue by jdillman1989** [FVANCOP/ChartNew.js#274]
The data I'm displaying in the chart uses some really long numbers in a short space. How can I abbreviate thousands and millions using "k" and "m" for the inGraphData? Here's what I've tried:

	function computeInGraphTmpl(area, ctx, data,statData, posi,posj,othervars) {
		var format = (data / 1000) + "k";
		return format
	}

	var options = {
		inGraphDataShow : true,
		inGraphDataTmpl : computeInGraphTmpl,
	}

This gave me a function error here: 

	// Convert the template into pure JavaScript
	str.replace(/[\r\n]/g, "\\n")

I also tried this:

	var options = {
		inGraphDataShow : true,
		inGraphDataTmpl : "<%=(v3 / 1000) + 'k' %>"
	}

Which displayed NaN in the chart. Appreciate any help I can get on this issue, thanks!

**Comment by FVANCOP** [comment]
For your first attemp : It is a bit confusing, but templates options can not be a function but .... in the template, you can call a self written function.

     inGraphDataTmpl : "<%= myFunction(v3) %>"

     function myFunction(value) {
        newvalue=value/1000;
        return(newvalue+" K");
     }

For your second attempt, it works on my browser (Firefox) and so I cannot reproduce your problem. But, it is probably related to the fact that the formula is not well understood by your browser. If you try inGraphDataTmpl : "<%= (v3/1000) %>", I think that it will work. But when you add "+ 'k'", it tries to interprete 'k' as a number. Perhaps that this will work better on your browser : "<%=(v3 / 1000).toString() + 'k' %>"

**Comment by jdillman1989** [comment]
Both of these methods are still returning as "NaN". I wonder if it has to do with the chart values being dynamically generated. I was able to achieve what I wanted by using a similar function server-side in PHP. Thanks for your help!

**Comment by jdillman1989** [comment]
I realized what my problem was. I was originally using the option `thousandSeparator : ","` in this project, before I decided to use abbreviated number formats. That option was causing the values to only be returned as strings. Removing that option allows me to run your function on `inGraphDataTmpl`.
