### ISSUE TITLE
Draw Text Through Graph - Responsive Support

### ISSUE THREAD

**Issue by cheeky-micah** [FVANCOP/ChartNew.js#275]
Hey There,

I like what you've done with all the extensions for Chart JS. I am just wondering if it's possible to have responsive support for the text that gets drawn, when doing the text through a graph. (Using doughnut graphs at the moment)

I tried resizing the window (with responsive option turned on, but the text doesn't resize with the graph).
Wondering if there is currently a solution?

Thanks!

**Comment by FVANCOP** [comment]
Hi,

In current version, resizing the window will only resize the graph part and not the font size (and other parameters related to the size). But I'm convinced, that I need to implement it.... but it is a big work (size is referred almost everywhere....)

**Comment by cheeky-micah** [comment]
No worries!  Thanks again for the effort on charts! :D

**Comment by FVANCOP** [comment]
Your request has been implemented !

Download the last version and set option responsiveScaleContent to true (default value is false).

**Comment by cheeky-micah** [comment]
Awesome, thank you!
