### ISSUE TITLE
updateChart() does not work with responsive=true

### ISSUE THREAD

**Issue by henrythasler** [FVANCOP/ChartNew.js#276]
When updating chart data using the updateChart() function while responsive=true the old data is restored after a resize event.

see http://jsfiddle.net/drgruL1n/
wait 2 seconds; resize the output frame; old data is restored.

hint: jsGraphResize needs to be updated in updateChart() to solve this issue

**Comment by FVANCOP** [comment]
Problem has been fixed in the last version. Sorry for the so long delay.
