### ISSUE TITLE
Creating a fixed horizontal line on a line graph

### ISSUE THREAD

**Issue by georgyj** [FVANCOP/ChartNew.js#277]
Hi,

I wanted to know if is possible to draw a fixed line on a line graph, without having to plot the actual points. I've looked through the documentation and did not see anything (or I overlooked it). 

Example: 

Say I have generated a graph for a person's blood pressure data. And both diastolic and systolic have lows and high (70 to 190 and 40 to 100, respectively), which are constant values. Is there a way I can lines (without data points) that how on horizontally at 40, 70,90, and 100? Is this possible with current version of ChartNew?

Thanks

**Comment by FVANCOP** [comment]
Yes :-) 

Specify transparent color for the point : 

Example : 

	datasets : [
		{
			fillColor : "rgba(0,0,0,0)",
			strokeColor : "red",
			pointColor : "rgba(0,0,0,0)",
			pointStrokeColor : "rgba(0,0,0,0)",
			data : [90,,,,,,90],
                        title : "90 value"
		},

**Comment by georgyj** [comment]
Ahh! Good idea! 

Thanks
