### ISSUE TITLE
ie8 error!

### ISSUE THREAD

**Issue by lramos1994** [FVANCOP/ChartNew.js#282]
SCRIPT5007: Unable to get the value of property 'xPos': object is null or undefined. only on horizontal bar.

**Comment by FVANCOP** [comment]
Can you send your code to my mailbox ? I will try to find an IE8 emulator on the web in order to reproduce the problem and to find a solution.

Regards,
François

**Comment by FVANCOP** [comment]
Problem solved - Problem in the data not in ChartNew.js
