### ISSUE TITLE
Pie chart crossText not using thousandSeparator

### ISSUE THREAD

**Issue by jdillman1989** [FVANCOP/ChartNew.js#286]
I'm using a pie chart with `crossText` in the center that displays the total of it's data values. This usually comes out to a number in the millions, but doesn't have any thousand separator commas. I using the `thousandSeparator` option to indicate the commas for the `crossText` value, but it isn't working.

	function crossTextFunction(numtxt,valtxt,ctx,config,posX,posY,borderX,borderY,overlay,data,animPC){

		var totalData = parseInt(data[0].value) + parseInt(data[1].value) + parseInt(data[2].value);

		if(numtxt==0) return(Math.round(animPC*totalData));
	}

	var pieOptions = {

		crossText : ["%dispdata"],
		crossTextIter: ["all"],
		crossTextFontSize : [12],
		crossTextFontColor : ["black"],
		crossTextRelativePosX : [2],
		crossTextRelativePosY : [2],
		crossTextAlign : ["center"],
		crossTextBaseline : ["middle"],
		crossTextFunction : crossTextFunction,

		thousandSeparator : ",",
	}

Is there any built-in way to format the `crossText` number? Am I using `thousandSeparator` incorrectly? If not, how might I manually script this formatting?

**Comment by FVANCOP** [comment]
The format function is never called when a value is computed by a user function. Moreover, for crossText, there is no possibility to change the value through automatic format. You have to do it yourself.

Simply change your program like this : 
           if(numtxt==0) return(fmtChartJS(config, Math.round(animPC*totalData),"none"));

**Comment by jdillman1989** [comment]
Ah, ok thanks. Working great now.
