### ISSUE TITLE
StackedBar - Bars not rendering correctly

### ISSUE THREAD

**Issue by Robsk** [FVANCOP/ChartNew.js#294]
I don't know if this is a bug, but with more and more datasets (and always the 
same amount of labels) in StackedBar, bars are rendered thinner and thinner until it reaches a certain width. Suddenly, if you continue with adding datasets, bars are rendered too wide and overlap each other (see images).

stackedBar with one dataset (Bars having normal width):
![stackedbarnormalbars](https://cloud.githubusercontent.com/assets/12694843/7911794/cbd84a66-0861-11e5-8ec9-3dc6530ec248.PNG)

stackedBar with 9 datasets (Bars are rendered thinner):
![stackedbarthinbars](https://cloud.githubusercontent.com/assets/12694843/7911668/a63cdb9c-0860-11e5-92fe-e66e03e076bd.PNG)

stackedBar with 36 datasets (Bars are too wide):
![stackedbartoobig](https://cloud.githubusercontent.com/assets/12694843/7911517/1a7cca00-085f-11e5-8db5-0ebcfb19fe10.PNG)

**Comment by FVANCOP** [comment]
Thanks for reporting this bug.

It has been fixed in the last version.

Regards,
Francois

**Comment by Robsk** [comment]
Thank you :)
