### ISSUE TITLE
Annotations for overlapping points?

### ISSUE THREAD

**Issue by xingped** [FVANCOP/ChartNew.js#295]
Is there a way to display the annotations for every point in an area if multiple points are overlapping each other? Same for if using detectAnnotateOnFullLine.

**Comment by FVANCOP** [comment]
Nothing is foreseen to do that. But it could be implemented (not really easy but not impossible) through a self written function.

        Init option "annotateLabel : myAnnotateFunction"

        function myAnnotateFunction(area, ctx, data,statData, posi,posj,othervars) { 
            var displayValue="";
            <write here the code that computes what has to be displayed in annotate for (posi,posj)>;
            return displayValue;
         }

**Comment by xingped** [comment]
I may look into using a function then. Thank you!
