### ISSUE TITLE
updateChart() fails if animation = true and the chart is in the middle of an animation

### ISSUE THREAD

**Issue by xingped** [FVANCOP/ChartNew.js#296]
If I have animation = true for the chart options and I call updateChart() while the animation is still ongoing from another updateChart() call, the subsequent updateChart() call will fail.

**Comment by FVANCOP** [comment]
Yes, it is the case... and I have no solution... You should wait until the animation is completed before the user could recall the function updateChart... I suppose that this can be achieved by specifying a function that unlocks the updateChart calls when the animation is completed.

Something like this : 

     var lockUpdate=false;
     (...)

     function unlockupdate(ctx, config, data, movement, animationCount) {
        lockupdate=false;
     }


     [set option "onAnimationComplete : unlockupdate"]
     (...)
     if(lockupdate==false) {
            lockupdate=true;
           // set 5th paramater to true => the "onAnimationComplete function is called
          // when the animation is finished.
           updateChart(ctx,data,config,true,true);
     }
 

        function unlockupdate(ctx, config, data, movement, animationCount) {
        lockupdate=false;
        }

**Comment by xingped** [comment]
Okay, thanks!
