### ISSUE TITLE
problem in bar border radius in negative value

### ISSUE THREAD

**Issue by omarsedki** [FVANCOP/ChartNew.js#298]
the semi circle need to be reversed .
![chart 2](https://cloud.githubusercontent.com/assets/8490104/7953925/59deb7f6-09d3-11e5-8544-e4e9afc96b44.png)

**Comment by FVANCOP** [comment]
Sorry Omar - but it seems that I forgot to mention that the problem has been solved in one of the last version.

Thanks for reporting the problem !

**Comment by omarsedki** [comment]
thanks
