### ISSUE TITLE
Move mouse over annotation with mouseMove action and turning series on/off

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#301]
Hello! Thanks again for new chart library.
Is there opportunity to move over the hint with mouse (over annotateLabel)?

Example with css code:
style:
a {
position:relative;
}
a span
{
display:none;
}
a:hover span
{
position:absolute;
display:inline;
border: 1px solid #0000FF;
margin: 0px 0px 0px 10px;
background: #faffc3;
right:0;
margin-right: 105%;
}

html:
&#60;div&#62;
Some text, 
&#60;a href="#"&#62; link &#60;span&#62; Hint.Second line of hint.&#60;/span&#62; &#60;/a&#62;
, some text.
&#60;/div&#62;

It works almost like this in mouseDown action, but I need to click on it.

And is there opportunity to turn series on/off, for example, with some buttons?

Thanks!!

**Comment by FVANCOP** [comment]
Hi ! 

It is difficult to implement something like that... I have performed several tests, but I did not succeed to achieve a good result. But.... I have implemented two new options : 

annotateFunctionIn and annotateFunctionOut - see https://github.com/FVANCOP/ChartNew.js/wiki/100_020_Annotations#annotatefunctionin

Perhaps that this could help to solve your issue ?

See also in Samples\annotateFunction.html

Regards,
François

**Comment by luna2761** [comment]
annotateFunctionIn and annotateFunctionOut  didn't work - no alert messages appeared((.

Thank you

**Comment by FVANCOP** [comment]
Did you test Samples\annotateFunction.html ? For me, it works on Firefox and IExplorer 11.

If you move the mouse over the points or over the bar/pie areas on the sample, it should display a message box. 

Try to move over the bars in the bar chart or the pie/doughnut; It is less obvious on Line and PolarArea charts.

**Comment by luna2761** [comment]
Yes, Samples\annotateFunction.html works fine.

Thank you.
