### ISSUE TITLE
Linear regression for date type data in xPos

### ISSUE THREAD

**Issue by Alan01252** [FVANCOP/ChartNew.js#304]
Hi all,

Has anyone managed to get linear regression working when you have xPos which is made up of an array of Date objects?

At the moment it fails because the Math is stats.js won't work with Date objects you just get NAN for the linear_regression_b1 and b0 fields.

Cheers

Alan

**Comment by FVANCOP** [comment]
Without any change to the code, I could produce a linear regression for date/time data. But it was not easy to find the solution...

See sample in Samples\linear_regression_date.html.

@Alan01252 : please close the issue if the proposed solution is OK for you.

(do not forget to include the add-in "format.js" in your code).

Usefull documentation to understand the code : 

https://github.com/FVANCOP/ChartNew.js/wiki/900_020_statistics   -> Explains the regression usage
https://github.com/FVANCOP/ChartNew.js/wiki/900_010_format.js   -> Explains function fmtChartJSPerso and "FMTDATETIME DD/MM/YYYY HH:mm"
https://github.com/FVANCOP/ChartNew.js/wiki/120_Template_variables -> Explains variable lgtxt2

**Comment by Alan01252** [comment]
This is awesome, thank you so much :) Is there anyway I can donate to this library? I had a look but nothing was obvious?

**Comment by FVANCOP** [comment]
Donate ? I appreciate your proposal but ... I do this for my pleasure ; I'm grateful to you if you use ChartNew.js and if you promote it on the web :-)

**Comment by Alan01252** [comment]
Thanks @FVANCOP I will do :)
