### ISSUE TITLE
legend for stacked bar chart

### ISSUE THREAD

**Issue by mgkimsal** [FVANCOP/ChartNew.js#305]
var opt3 = {
        legend:true,
        showSingleLegend:true,

    };
    var data3 = {
        labels : ["2015-06-02","2015-05-28","2015-05-26"],
        datasets : [
            
            {
                fillColor : ["#66aa66","#99CC99"],
                strokeColor : ["#66aa66","#99CC99"],
                data: [7, 20],
                title: "foo"
            },
            
            {
                fillColor : ["#66cc66","#cc9966"],
                strokeColor : ["#66cc66","#cc9966"],
                data: [81, 6],
                title: "foo"
            },
            
            {
                fillColor : ["#333399"],
                strokeColor : ["#333399"],
                data: [1],
                title: "foo"
            },
            

        ]
    };

    var myLineChart2 = new Chart(ctx2).HorizontalStackedBar(data3, opt3);

All of my legends are 'foo', because that's what I'm titleing them, as you can see.  But I don't see any way to pass multiple legend labels.  The legend seems to require the 'title' attribute from a dataset, but there's multiple pieces of data in a dataset - the legend seems like it would need to take an array in 'title' if there's multiple data points in a specific dataset.  I'd expect to be able to do something like:

      fillColor : ["#66cc66","#cc9966"],
                strokeColor : ["#66cc66","#cc9966"],
                data: [81, 6],
                title: ["foo",'bar']
            },

so "bar" would have a legend color of "cc9966" and "foo" would have a legend color of "66cc66"

I'm probably thinking about this wrong, but can't be the only person who's having trouble with stacked bargraph legends. (or maybe I am?)

![screen shot 2015-06-12 at 4 43 26 pm](https://cloud.githubusercontent.com/assets/75154/8139493/3437bccc-1122-11e5-8aee-118055e37ae1.png)

**Comment by FVANCOP** [comment]
Hi Michael,

The code for displaying the legend in the chart is really not a easy part... and changing the colors for each bar is a possibility given by ChartNew.js that is not widely used. When the color is changed through array definitions, the legend is not correct (it will be so for chart types), but I fear that changing the code will introduce lot of new bugs... So I prefer to leave the code unchanged for that part... If the colors are changed, I assume that poeple will not diplay the legend on the chart....

If you set the data like this you got a better result : 

           var data3 = {
               labels : ["2015-06-02","2015-05-28","2015-05-26"],
               datasets : [
                   {
                       fillColor : "blue",
                       strokeColor : ["#66aa66","#99CC99"],
                       data: [7, ],
                       title: "foo1"
                   },
                   {
                       fillColor : "black",
                       strokeColor : ["#66aa66","#99CC99"],
                       data: [, 20],
                       title: "foo1"
                   },
                   {
                       fillColor : "red",
                       strokeColor : ["#66cc66","#cc9966"],
                       data: [81, ],
                       title: "foo2"
                   },
                   {
                       fillColor : "yellow",
                       strokeColor : ["#66cc66","#cc9966"],
                       data: [, 6],
                       title: "foo2"
                   },
                   {
                       fillColor : "green",
                       strokeColor : ["#333399"],
                       data: [1],
                       title: "foo3"
                   },
               ]
           };

![canvas](https://cloud.githubusercontent.com/assets/6121933/8146144/c003228e-1229-11e5-8f51-f18922b56f57.png)
