### ISSUE TITLE
ie8 issues

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#307]
Hi!

I'm using line chart and it works in Chrome & ie11.
But in ie8 it doesn't work correctly and indicates an error: "Unable to get property 'data' of undefined or null reference. File: chartNew.js, Line: 2733, Column: 51".

annotateLabels do not work at all, they are created this way: https://github.com/FVANCOP/ChartNew.js/issues/299

I'm using excanvas.js as proposed in documentation. path to this script is correct (&#60;!--[if lte IE 8]&#62;&#60;SCRIPT src='excanvas.js'&#62;&#60;/script&#62;&#60;![endif]--&#62;)

**Comment by FVANCOP** [comment]
Hi @luna2761 ,

Sorry for the long delay; But is not easy for me to find a version of IExplorer 8 (I use "IE tester" but is not easy to debug).

In the last version, two issues encountered with IExplorer have been fixed.

-> The default background color for annotate is "annotateBackgroundColor: 'rgba(0,0,0,0.8)'", but RBGA colors are not allowed for "div" background colors in IExplorer 8;
-> line charts were not correct;

If you have other issues (there are probably other issues with IExplorer 8), can you send me your  code (options and data) ?

Thanks,
François
