### ISSUE TITLE
Android only : cavas grows in size the second time using new Chart(ctx).Line(graphSet,opt) on same canvas

### ISSUE THREAD

**Issue by EvEggelen** [FVANCOP/ChartNew.js#309]
This is Android specific bug. This happens on mobile Android (4.x - 5.x) devices in the native web browser or in a webview. This is even the case when using the latest mobile Firefox (for Android) that uses it own rendering engine.

I was not able to reproduce it on iOS devices, or on any of my PC browsers.   

Problem: When the new Chart(ctx).Line(graphSet,opt) is used for the first time on the canvas, everything works as specified (cavas is expanded to the correct size). However the canvas will be expanded every time new Chart(ctx).Line(graphSet,opt) is called on the same canvas. If you do this enough, the browsers fails due to memory issues. When updateChart(ctx,graphSet,opt,true,true)  is used for the second (or later), it works as specified.

On request I can provide an URL that demonstrates the issue. 

```javascript
var floatGraphDataset   = {"GRAPH1":{"name":"GRAPH1","txt":"Float V1","graph":{"labels":[32,64,256,512],"datasets":[{"label":"GRAPH1","fillColor":"rgba(220,220,220,0.2)","strokeColor":"rgba(128,128,128,1)","pointColor":"rgba(100,100,100,1)","data":[64.962,64.415,62.233,56.583]},{"label":"GRAPH1","fillColor":"rgba(220,220,220,0.0)","strokeColor":"rgba(64,64,192,1)","pointColor":"rgba(200,200,200,0)","data":[64.916,64.916,64.916,64.916]}]}},"GRAPH2":{"name":"GRAPH2","txt":"Float V4","graph":{"labels":[32,64,256,512],"datasets":[{"label":"GRAPH2","fillColor":"rgba(220,220,220,0.2)","strokeColor":"rgba(128,128,128,1)","pointColor":"rgba(100,100,100,1)","data":[77.021,62.72,62.205,56.011]},{"label":"GRAPH2","fillColor":"rgba(220,220,220,0.0)","strokeColor":"rgba(64,64,192,1)","pointColor":"rgba(200,200,200,0)","data":[63.646,63.646,63.646,63.646]}]}}};

var setopts = {
      responsive: true,
      responsiveWindowInitialWidth: true,
      //responsiveScaleContent: true,
      maintainAspectRatio: true,
      animation : false,
      showTooltips : false,
      annotateDisplay: true,
      annotateLabel : "<%=v3%>",
      annotateRelocate : true,
      datasetFill : false,
      legendBlockSize : 50,
      scaleLabel: "<%=value%>",
      canvasBorders : true,
      canvasBordersWidth : 3,
      canvasBordersColor : "black",
      legend : false,
      graphMin : 0,
      yAxisMinimumInterval : 1,
      scaleFontSize : 10,
      scaleFontFamily : "sans-serif"
}

function drawFloat(selected) {

    var ctx=document.getElementById("f").getContext("2d");
    var graphSet=floatGraphDataset[selected].graph;
    var opt=setopts;
    if (bFirstDrawFloat==false) {
        updateChart(ctx,graphSet,opt,true,true);
    } else {
        if (graphSet.labels.length >0) {
            bFirstDrawFloat=false;
            var myLine1 = new Chart(ctx).Line(graphSet,opt);
        }
    }
}

<meta name="viewport" content="initial-scale=1" >

<canvas id="f" height="100" width="100" ></canvas>

```

CharNew version from master ( 15 june 2015) was used.

**Comment by FVANCOP** [comment]
I know there are problems with portable devices but have currently no solution.

Perhaps check following issue : https://github.com/FVANCOP/ChartNew.js/issues/213

**Comment by FVANCOP** [comment]
@EvEggelen : as proposed, can you (or someone else) provide an URL where you have the problem ? I have performed several test, but could not reproduce it on my device.

URL with my tests : 
http://www.favomo.be/graphjst/index.html
http://www.favomo.be/graphjst/index_V1.html
http://www.favomo.be/graphjst/index_V2.html 

Attention: those tests will be removed in some days.

**Comment by EvEggelen** [comment]
I tested the 3 URLS that are listed below. On a Samsung Galaxy S4 running Android 5.0.1 (latest update for that device) i see the following on all 3 URLs while using the standard browser: The graphs start O.K. but after a few seconds they start to grow (in steps) till the screen becomes blank (guess out of memory or so). What I see is inline what I noticed with my own pages on many mobile devices.

Did you try to reproduce it on iOS devices. If I recall correctly, it worked O.K. on some iOS devices (as on my desktop)

---- On Tue, 07 Jul 2015 23:12:08 +0200 Francois Vancoppenolle &lt;notifications@github.com&gt; wrote ---- 

@EvEggelen : as proposed, can you (or someone else) provide an URL where you have the problem ? I have performed several test, but could not reproduce it on my device.
 URL with my tests : 
 http://www.favomo.be/graphjst/index.html
 http://www.favomo.be/graphjst/index_V1.html
 http://www.favomo.be/graphjst/index_V2.html 
 Attention: those tests will be removed in some days.

**Comment by FVANCOP** [comment]
I found that there is problem with Retina device; Perhaps that the change that I have performed to solve it will also solve the problem that you have on your device.

Can you retry the 3 links : 

URL with my tests :
http://www.favomo.be/graphjst/index.html
http://www.favomo.be/graphjst/index_V1.html
http://www.favomo.be/graphjst/index_V2.html

Thanks for your cooperation,
François

PS : on following branch, you will find the version that I will publish if the 3 links are OK for you
https://github.com/FVANCOP/ChartNew.js/tree/updatechart_retina_device

**Comment by EvEggelen** [comment]
I tested these URLs on 3 different Android devices (1 x mobile, 2 x 
tablet). On these devices the "growing" problem is solved. This is 
great. Thanks.

On (current, including 5.0.1 ) Android you need to disable HW 
acceleration for a webview when you want to use a canvas. So this means 
the canvas rendering is done is SW. When the device has a very high 
resolution screen >=720p, up to 4k, this becomes painful. For this I 
wanted to render at defined resolution e.g. 640x640 and let the HW scale 
the cancas to the native resolution of the screen. I tried to accomplish 
this with ChartNew, but so far I was not able to do this. Even when the 
responsive was set to false. But it would also be helpfull if there was 
a subsampling factor when using (responsive: true, 
responsiveWindowInitialWidth: true, responsiveScaleContent: true). This 
would increase responsiveness/animations for high resolution screen 
(e.g. 4K for a tablet)

Can you confirm that ChartNew lib always renders at the native 
resolution of the screen.

**Comment by FVANCOP** [comment]
@EvEggelen : GREAT THANKS for your test and (quick) feedback ! The changes that have been tested are now integrated in the official version. 

I'm not a specialist of Android; It is a bit difficult for me to understand what is possible or not with android...
 
If I do well understand : 
-> on Android, when HW acceleration is enabled, you can't use canvas; So you may not enable HW acceleration.  

-> Without HW acceleration, when the resolution of the screen is high, the display is slow. You tryed to reduce the resolution, but you did not achieve to reduce the resolution. Perhaps can someone help you - Sorry, but I can't....

-> If it is slow when the resolution is high, you can reduce the number of steps in the animation (animationSteps : 30) or even suppress the animation (animation : false) 

-> 3 options can help you to simulate a lower resolution of the chart when you have a high resolution screen (default value for those 3 options is 1 ; Set it to a value greater than 1 to simulate a lower resolution).

		chartTextScale : 1,   -> Scale factor for the text size
		chartLineScale : 1, -> Scale factor for the line width
		chartSpaceScale : 1, -> Scale factor the the "space" options.
