### ISSUE TITLE
Vertical Line on canvas in front

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#310]
Hi!

Could you, please, tell, if it is very complicated to draw vertical separate line on chart, colored to some color, on one of vertical gridlines in front?
How should I change this code or may be use better one?
ctx1.beginPath();
ctx1.moveTo(200, 10);
ctx1.lineTo(200, 150);
ctx1.stroke();

Thank you

**Comment by FVANCOP** [comment]
It is probably possible to draw lines using the technique that you propose, but ofcourse, if the design of the chart changes (more or less spaces on the right, on the top), your lines will appear on other places...

The xPos technique car be used for drawing lines. See  https://github.com/FVANCOP/ChartNew.js/wiki/070_010_Line

Example : 

          var mydata1 = {
          	labels : [0,5,10,15,20,25,30],
            	datasets : [
          		{
          			pointColor : "black",
                    			strokeColor : "rgba(255,255,0,100)",
                    			pointStrokeColor : "black",
                    			data : [13,18,15,25,18,13,5],
                			title : "points"
          		},
          		{
          			pointColor : "rgba(0,0,0,0)",
                    			strokeColor : "red",
                    			pointStrokeColor : "rgba(0,0,0,0)",
                    			data : [0,40],
                			xPos : [10,10],
                			title : "Vertical Line 1"
          		},
          		{
          			pointColor : "rgba(0,0,0,0)",
          			strokeColor : "red",
          			pointStrokeColor : "rgba(0,0,0,0)",
          			data : [0,40],
                			xPos : [16,16],
                			title : "Vertical Line 2"
          		}
          	]
          }               


![canvas](https://cloud.githubusercontent.com/assets/6121933/8217440/c8d1b5ee-153d-11e5-8835-891b4f95af65.png)

**Comment by luna2761** [comment]
I've tried xPos technique on simple line graph, it worked with xBegin and xEnd parametrs.  
However, if I have BarLine type, that doesn't work. It draws bars by default, and if I use type:"Line" in dataset, no vertical lines are drawn. Any help? =) 

Thank you.

**Comment by FVANCOP** [comment]
Hi,

I did never test xPos for Bar charts; I have tested it and indeed, there was a problem. It has been fixed in the last version (a variable was missing). Can you try it with the last version ?

François

**Comment by luna2761** [comment]
I've tried with the last version of ChartNew.js, but it doesn't work properly:

<pre>
var mydata1 = {
    labels : ["January","February","March","April","May","June","July"],
xBegin:30, xEnd:800,
    datasets : [
        {
            type: "Line",
            fillColor : "rgba(0,200,0,1)",
            strokeColor : "rgba(0,200,0,1)",
            pointColor : "rgba(0,200,200,1)",
            pointstrokeColor : "green",
      axis : 2,
            data : [95,53,99,,73,27,82,],
      title : "2014"
        },
        {
            fillColor : "rgba(151,187,205,0.5)",
            strokeColor : "rgba(151,187,205,1)",
            pointColor : "green",
            pointstrokeColor : "yellow",
            data : [35,43,59,,31,50,66],
      axis : 1,
      title : "2013"
        },
        { 
        type:"Line", 
        pointColor : "rgba(0,0,0,1)", 
        strokeColor : "red", 
        pointStrokeColor : "rgba(0,0,0,0)", 
        data : [35,70], 
        xPos:[10,10], 
        title : "Vertical Line 1", axis:1 }, 
        { 
        type:"Line", 
        pointColor : "rgba(0,0,0,1)", 
        strokeColor : "red", 
        pointStrokeColor : "rgba(0,0,0,0)", 
        data : [55,70], 
        xPos : [40,40], 
        title : "Vertical Line 2", axis:1 } 
    ]
}    
</pre>
![capture](https://cloud.githubusercontent.com/assets/10071245/8453345/65ba438a-1ffc-11e5-8140-540211c04e29.PNG)

**Comment by FVANCOP** [comment]
You set xBegin to 30, but for "vertical line 1", you specifies "xPos:[10,10]" which is lower than your begin (10 < 30) !!! If you set  xBegin to a value lower or equal to 10, it will be correct (xBegin is the middle of the first Bar and xEnd is the middle of the last bar). When xBegin is greater than xPos values, xPos value are ignored. That's what is happening here.

**Comment by luna2761** [comment]
Many thanks! !!! Works great.
