### ISSUE TITLE
Convert HTML table to chart

### ISSUE THREAD

**Issue by mehdihaddad** [FVANCOP/ChartNew.js#311]
I think it can be possible to convert HTML table with an ID to a Chart !
If you can work on it, it will be so cool !

**Comment by FVANCOP** [comment]
Hi,

Perhaps you can check in this other repository. It does not use ChartNew.js but Chart.js; Perhaps that it can be easely updated to use ChartNew.js.

Repository : https://github.com/Wikunia/Table2Chart
