### ISSUE TITLE
Mouse click on X axis and labels on X axis 

### ISSUE THREAD

**Issue by Nyde18** [FVANCOP/ChartNew.js#312]
Is it possible to create a click event on the x axis and on the labels there?

**Comment by FVANCOP** [comment]
In current version, it is not possible; But I will try to implement it (it should not be much difficult).

**Comment by FVANCOP** [comment]
You can now call a function when you click on text.

A new option as been added for it : detectMouseOnText

see : Samples\clicktextwithmouse.html - In this sample, it displays lot of information when you click over a text in a chart.

Documentation : https://github.com/FVANCOP/ChartNew.js/wiki/100_095_Mouse_Actions
