### ISSUE TITLE
mouseDownLeft option provides other == null if click placed on data

### ISSUE THREAD

**Issue by nxthor** [FVANCOP/ChartNew.js#314]
Hello!
I am trying to link to different URLs when clicking on each slice of a pi-chart.
So far I have found the hook for mouseDownLeft and assigned a custom function taking the 5 parameters, but 'other' will be null - even if I clicked on a slice.
I guess the other-content is decided by collision-test or similar by coordinates of the click.

Is there any circumstance in which the positioning may be off, or the hook won't be provided with an object for other?

As soon as I can read the other.v1 content, I can redirect the location to the designated URL.

**Comment by FVANCOP** [comment]
You probably have a mistake somewhere.

This works fine for me : 

          function mouseLeft(event,ctx,config,data,other)
          {
                    if(other != null) {
                              window.alert(other.i);
                    }
          };

          function mouseRight(event,ctx,config,data,other)
          {
                    if(other != null) {
                              window.alert(other.v1);
                    }
          };

          var newopts = {
                inGraphDataShow : true,
                canvasBorders : true,
                canvasBordersWidth : 3,
                canvasBordersColor : "black",
                graphTitle : "Graph Title",
                legend : true,
                annotateDisplay : true, 
                mouseDownLeft : mouseLeft,
                mouseDownRight : mouseRight 
          };

          var myLine = new Chart(document.getElementById("canvas_pie").getContext("2d")).Pie(mydata2,newopts);

**Comment by davelkan** [comment]
Hi,

I really appreciate your work on this library, but sadly i am having the same issue. I can only get other to obtain a value besides null when i have enabled "detectMouseOnText", and then of course only when i click on text.  I am trying to implement page changes based on the segment of graph clicked.  Here's some code:

```javascript
function generateChart() {
    options = {
        animation: false,
        mouseDownLeft: fctMouseDownLeft,
    }
   #these functions generate the data used by the chart
    var data = assembleChartData(gatherChartData());
    var ctx = $("#myChart").get(0).getContext("2d"); 
    activeChart = new Chart(ctx).Doughnut(data,options);
}

#currently just printing everything to figure out what's going on
function fctMouseDownLeft(event,ctx,config,data,other)
{
    console.log("event: ",event)
    console.log("canvas: ",ctx)
    console.log("config: ",config)
    console.log("data: ",data)
    console.log("other: ",other)
    if(other != null){
        console.log("other was not null");
    }
    else {
        console.log("other was null")
    }
}
```

clicking anywhere on the graph logs all the values successfully, but other is consistently reported as null

Any insights would be greatly appreciated,

Thanks,

David

**Comment by nxthor** [comment]
My ugly workaround was to do some math with the click-coordinates since I had a nice centered piechart with 5 equal sized parts, that are not dynamic. Pythagoras saved the day - thank you teacher from the past :)
I will also never touch that code again, so my problem is gone so far, but it would be nice to know, if there is something wrong in the piechart that we only got null-values out of the clicks using the hook.

**Comment by davelkan** [comment]
By a setting annotateDisplay to true i got it working, but with a highly undesirable toolTip.  Couldn't figure out how to remove it so I ended up digging through the source code and commenting out the lines in annotateDisplay that created the tootlTip.  Better solution would be to create a new option that replicates the functionality of annotateDisplay, but without the tooltip  Don't really have the time to focus on that right now unfortunately so i'm running with my hack for now.

**Comment by FVANCOP** [comment]
Hi @davelkan 

This is a bug; Without setting annotateDisplay to true, the 'other' variables should be initialized. I will fix  this when I'm back from my holidays.

Temporarily, you can hide the tooltip by setting following options : 
      annotateLabel: "<%=' '%>",
      annotateBackgroundColor:"rgba(0,0,0,0)",

**Comment by FVANCOP** [comment]
Problem has been fixed in last version; It is no more necessary to set option annotateDisplay to true.

@davelkan   : Thanks for the debugging.
