### ISSUE TITLE
Label Overlap And Remove Decimal On Pie Charts

### ISSUE THREAD

**Issue by ulysnep** [FVANCOP/ChartNew.js#315]
Hi!

I have two questions/asks:

1. Is there a quick way to remove decimals from pie charts?
2. How do I fix graphs so labels do not overlap with one another?

Great chart js, really appreciate all your time!
![labels](https://cloud.githubusercontent.com/assets/8585209/8293606/8352fbb6-18eb-11e5-94a0-4c4197821c01.png)

**Comment by FVANCOP** [comment]
Hi,

Thanks for using ChartNew.js :-)

Q1 : set option roundPct to 0 (see https://github.com/FVANCOP/ChartNew.js/wiki/100_050_Format#roundnumber)
Q2 : this is more complicate... and not simple to resolve. See issue https://github.com/FVANCOP/ChartNew.js/issues/165

Regards,
François

**Comment by ulysnep** [comment]
Thanks! Really appreciate your quick response!
