### ISSUE TITLE
scaleSteps without scaleOverride

### ISSUE THREAD

**Issue by XescuGC** [FVANCOP/ChartNew.js#316]
Is it possible to set the scaleSteps without the scaleOverride? or there is another workaround to achieve the same efect of the scaleSteps in the general options? I couldn't find the option on the documentation.

Thanks

**Comment by FVANCOP** [comment]
scaleSteps can only be used with scaleOverride.

Other options can perhaps help you :
graphMax :  https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmax 
graphMin : https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#graphmin
yAxisMinimumInteral - https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#yaxisminimuminterval
