### ISSUE TITLE
Line Chart - Data series without label for each point

### ISSUE THREAD

**Issue by iPunjabi** [FVANCOP/ChartNew.js#319]
Hi,
How I can skip labels in data series. 
I am looking -> Line Chart - Data series without label for each point
similer like link below
https://github.com/nnnick/Chart.js/issues/12 
Thanks

**Comment by FVANCOP** [comment]
new options showXLabels, showYLabels, firstLabelToShow, firstYLabelToShow added.

See wiki documentation: 
https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#firstlabeltoshow
https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#firstylabeltoshow
https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#showxlabels
https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#showylabels
