### ISSUE TITLE
Add half Pie chart

### ISSUE THREAD

**Issue by iPunjabi** [FVANCOP/ChartNew.js#320]
Is it possible to Add half Pie or half dial chart. Please add it or let me know how I can help you to add more charts. that will be so usefull.
Thanks

**Comment by FVANCOP** [comment]
Hi,

I did not specify a new chart type, but a new option has been created : totalAmplitude. With this option, you can do more than half Pie :-)

Example : Samples\half_pie.htlm
Documentation : https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#totalamplitude
