### ISSUE TITLE
Superimpose Text On Top of StackedBar Graph

### ISSUE THREAD

**Issue by ulysnep** [FVANCOP/ChartNew.js#323]
Hello again!

Is there any way to superimpose text on top of the stackedbar graph (e.g. percentage)? Or is there a way to only show only the top ingraphdata and adjust the padding so that it appears on the very top of the stackedbar?

Thanks again for all your help and any guidance!
![text_placement](https://cloud.githubusercontent.com/assets/8585209/8470033/c4d23b38-2039-11e5-9a34-446cb2cd868f.png)

**Comment by FVANCOP** [comment]
I don't understand exactly what you want, but I think it is something like that : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/8483039/0e521e90-20ee-11e5-803c-e0f40e517261.png)

This has been achieved with following code : 

var mydata = {
    labels : ["January","February","March","April","May"],
    datasets : [
        {
        	fillColor : "green",
        	data : [70,40,20,10,5],
        },
        {
        	fillColor : "blue",
        	data : [10,20,20,20,25],
        },
        { 
	        fillColor : "orange",
	        data : [5,10,15,20,20], 
	}, 
        { 
		fillColor : "lightgray",
        	data : [15,30,45,50,50], 
	} 
    ]
}    


function mytemplate(area, ctx, data,statData, posi,posj,othervars) {
	if(posi==data.datasets.length-1 && statData[posi][posj].cumvalue>0) {
		vl=100*(statData[posi][posj].cumvalue-statData[posi][posj].datavalue)/statData[posi][posj].cumvalue;
		return("<%="+vl+"+' %'%>");
	} else return("");
};

var options = {
	graphSpaceBefore : 15,
	inGraphDataPaddingY : 3, 
	inGraphDataVAlign : "bottom" ,
	inGraphDataShow : true,
	inGraphDataTmpl : mytemplate
};


Documentation : 
graphSpaceBefore : https://github.com/FVANCOP/ChartNew.js/wiki/100_120_Spacing_Layout#graphspacebefore

IngraphData options : https://github.com/FVANCOP/ChartNew.js/wiki/100_080_In_Graph_Data

statData variables : https://github.com/FVANCOP/ChartNew.js/wiki/120_Template_variables

**Comment by ulysnep** [comment]
Wow! This is exactly what I was looking for! 

Thank you again for all your help!
