### ISSUE TITLE
Tooltip per line

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#325]
Hi again! =)

I wonder if it is very complicated to make tooltips (annotations) not per point, but per line (vertical, like in Chart.js) without totally reconfiguring chartnew.Js script?

**Comment by FVANCOP** [comment]
Unfortunately for you ...., you are too late to request it... It is already implemented :-) - see issue #211 

You have to use option detectAnnotateOnFullLine. 

See : https://github.com/FVANCOP/ChartNew.js/wiki/100_020_Annotations#detectannotateonfullline

There is also a sample in Samples\issue211.html.

**Comment by luna2761** [comment]
I have added this option and my graph stopped working. Maybe the reason is that I have Bar-line chart?

**Comment by FVANCOP** [comment]
I have added this option in Samples\stats_bar.html and it works fine on FireFox/IExplorer 11.

Can you send your HTML to my email address ?

Regards,
François

**Comment by luna2761** [comment]
I've tried Samples\stats_bar.html in IE11, but annotations there are unique, not one per line.

**Comment by luna2761** [comment]
It would be great if it works loke here: http://www.chartjs.org/docs/#line-chart (One annotation per line when mouse is anywhere on line)

**Comment by FVANCOP** [comment]
Yes, the option detectAnnotateOnFullLine is not activated in this sample (you had to activate it your self :-) ).

Another sample as been added that reflects your request.: Samples\bar_and_lines_with_detectAnnotateOnFullLine.html

**Comment by luna2761** [comment]
Sample works great. Many thanks!
