### ISSUE TITLE
Set line-height for the text In Graph (Chart) Data possible?

### ISSUE THREAD

**Issue by mediakreativ** [FVANCOP/ChartNew.js#336]
Hi there,

would it be possible to add a specific line-height for the text the "In Graph Data"?

I have added some breaks in the title, this works fine:

title : "lorem,\nipsum,\ndolor"
	},

and now it would be great if I could increase the distance between the 3 lines.

**Comment by FVANCOP** [comment]
No, this is not possible and too specific to be implemented.

You can put text where ever you want with options "crossText" - see https://github.com/FVANCOP/ChartNew.js/wiki/100_040_CrossText

In your case, you also have to use option spaceTop (see https://github.com/FVANCOP/ChartNew.js/wiki/100_120_Spacing_Layout )
