### ISSUE TITLE
Is it possible to set a simple 1px stroke around a pie? 

### ISSUE THREAD

**Issue by mediakreativ** [FVANCOP/ChartNew.js#337]
I found the other related issue about the "special sized" stroke - which is not possible right now. But is there an option to have a simple 1px stroke around the pie - or, alternatively, have an outside stroke for a particular segment?

**Comment by FVANCOP** [comment]
I think that this could be "simulated" with gradient color.

Take a look at issue https://github.com/FVANCOP/ChartNew.js/issues/227

Wiki for gradient color : https://github.com/FVANCOP/ChartNew.js/wiki/900_030_gradientColor.js
