### ISSUE TITLE
Set inGraphDataFontColor with function

### ISSUE THREAD

**Issue by mediakreativ** [FVANCOP/ChartNew.js#338]
I am trying to set the inGraphDataFontColor dydnamic in a pie chart with a function as displayed here:

https://github.com/FVANCOP/ChartNew.js/wiki/130_option_functions

Want to make it dependend on the value of the pie segment, but so far without success.

Here my code:

function fontColor(value) {
if(value == 500) return("red");
else return("white");
 }

...
var mydata2 = [
	{
		value : 300,
		color: "#999",
    title : "lorem"
	},
	{
		value : 500,
		color: "#9a024b",
    title : "ipsum"
	}
];

...

var opt3b = {
      animationStartWithDataset : startWithDataset,
      animationStartWithData : startWithData,
      animateRotate : true,
      animateScale : true,
      animationByData : true,
      animationSteps : 50,
      animationEasing: "easeOutQuint",
      canvasBorders : false,
      legend : false,
      inGraphDataShow : true,
      annotateDisplay : false,
      spaceBetweenBar : 5,
      inGraphDataShow : true,
      inGraphDataRadiusPosition : 1,
      inGraphDataPaddingRadius : 15,
      inGraphDataFontSize : 14,
      inGraphDataFontFamily : "Open Sans",
      inGraphDataFontColor : fontColor,
      inGraphDataAlign : "off-center",
      inGraphDataVAlign : "off-center",
      inGraphDataTmpl : "<%=v1%>",
      segmentShowStroke : false,
      crossImageOverlay : true,
      crossImageAlign : "center"
}

Any idea what is wrong?

**Comment by FVANCOP** [comment]
The parameter for function options is not the "value"; 

Check issue https://github.com/FVANCOP/ChartNew.js/issues/335 which is similar to your request.
