### ISSUE TITLE
updateChart Error

### ISSUE THREAD

**Issue by dhruv4** [FVANCOP/ChartNew.js#339]
Hey! First of all, this is a super awesome charting plugin. Thanks :)

I get this error when I try to dynamically update my chart. The chart stops updating. I think it might be that I'm trying to update the chart while it's being updated. Is there a way around this?

TypeError: undefined is not an object (evaluating 'statData[i][data.datasets[i].data.length-1].xPos')
drawLinesDatasetChartNew.js:5889:415
drawLinesChartNew.js:2892
animateFrameChartNew.js:4635
animLoopChartNew.js:4647

Thanks again!

**Comment by FVANCOP** [comment]
update a chart while another update is not completed is off course dangerous....

see issue #296 

Sorry for the long delay : I was on holiday.

Regards,
François

**Comment by dhruv4** [comment]
Oh I totally missed the other issue. I appreciate your answering!

Thanks!
