### ISSUE TITLE
Get Color From Other > Data > Color

### ISSUE THREAD

**Issue by ulysnep** [FVANCOP/ChartNew.js#342]
Hi again!

I'm trying to get the variable "color" from Other which is in an array and append to annotateLabel and I can't seem to reference it correctly. I've created a custom div for annotateLabel and I'm trying to call "color" within it.

     annotateLabel : "<%='<div id=\"tooltip\"><div class=\"tooltip_circle' + data.color + '\"></div>&nbsp;&nbsp;' + v1 + '&nbsp;&nbsp;&nbsp;<strong>' + v6 + '%</strong>&nbsp;&nbsp;&nbsp;</div>'%>",

**Comment by FVANCOP** [comment]
For Pie/Doughnut charts, use data[i].color; For Line/Bar charts, use data.datasets[i].fillColor 

annotateLabel : "<%='<div id=\"tooltip\"><div class=\"tooltip_circle'\"></div>&nbsp;&nbsp; Color=' + data[i].color+' ' + v1 + '&nbsp;&nbsp;&nbsp;<strong>' + v6 + '%</strong>&nbsp;&nbsp;&nbsp;</div>'%>",

Regards,
François

**Comment by ulysnep** [comment]
Excellent, works great! Thank you!

Best,
Aaron
