### ISSUE TITLE
Different error bars for each bar in a chart

### ISSUE THREAD

**Issue by samjjackson** [FVANCOP/ChartNew.js#343]
I have a dataset with four values, each of which has a different standard deviation associated with it. Is it possible to reflect this by having ChartNew draw four different length error bars, one for each bar in the chart? So far i have been able to create error bars of the same length using drawMathDeviation.

Thanks,
Sam

**Comment by FVANCOP** [comment]
Hi,

Not sure that I fully understand your request, but the following chart has been produced with new member Samples\math2.html.

![canvas](https://cloud.githubusercontent.com/assets/6121933/9282696/9289eaf6-42ce-11e5-9678-950cc52513a4.png)

If this is not what you are looking for, please give me more explanations (send me an email).

**Comment by samjjackson** [comment]
Thank you for your help, this is exactly what I needed.

Best wishes,
Sam

On 14 August 2015 at 20:54, Francois Vancoppenolle <notifications@github.com
