### ISSUE TITLE
X-Axis Interval Set to Only Integers

### ISSUE THREAD

**Issue by jspin77** [FVANCOP/ChartNew.js#344]
I am using the horizontal bar chart and would like the x-axis to only show integers. I saw the thread on this same issue for the y-axis and it appears that the same option is not available for the x-axis.  Would it be possible for you to add this in?  

Thanks for all the hard work on this project!  It's a great project.

**Comment by FVANCOP** [comment]
Hi,

It is a bit confusing, but for HorizontalBar and HorizontalStackedBar charts, the vertical axis has to be considered as the X Axis and the horizontal axis as the Y Axis... 

So option "yAxisMinimumInterval" works for the horizontal Axis. If you set  "yAxisMinimumInterval : 1", the horizontal axis will display only integer values.

Regards,
François

**Comment by jspin77** [comment]
Thanks for the response!
I had actually tried that and it still doesn’t work.  Is it possibly because I have overridden the scale?  Here are the options that I had set.  

                        responsive: true,                        scaleOverride: true,                        yAxisMinimumInterval:1,                        scaleSteps: 10,                        scaleStepWidth: ispMaxScale / 10,                        scaleIntegersOnly: true,                        scaleStartValue: 0,                        animation: true,                        showTooltips: true,                        savePng: true,                        legend: true,                        graphTitle: "Adjudications by ISP",                        inGraphDataYPosition: [5, 5],                        inGraphDataVAlign: ["bottom"],                        inGraphDataPaddingY: [13, 13],                        annotateDisplay: true,                        legendBorders: false
John
Date: Wed, 19 Aug 2015 13:22:09 -0700

**Comment by FVANCOP** [comment]
Yes, if you overwrite the automatic scale calculation, the yAxisMinimumInterval option is not used;

You got decimal values because scaleStepWidth is not an integer; 

Try this : scaleStepWidth: Math.ceil(ispMaxScale / 10)
