### ISSUE TITLE
Bar width

### ISSUE THREAD

**Issue by gavinspearhead** [FVANCOP/ChartNew.js#345]
Is it somehow possible to set the maximum width of a bar in a bar diagram? Eg set it to 20% of the width graph. I sometimes end up with bar graphs with only one bar and that looks a bit silly.

**Comment by FVANCOP** [comment]
You can use option spaceLeft and spaceRight to force free space on sides.

See : https://github.com/FVANCOP/ChartNew.js/wiki/100_120_Spacing_Layout

**Comment by gavinspearhead** [comment]
These are absolute values (pixels) right? And that would also move the axis to the middle of the canvas?
That is not gonna much help, I'm afraid, the canvas size (height and width) is dynamic, the number of bars as well. And I don't know the width of the Yaxis texts in advance as well. And I'm not sure it would actually look better.

**Comment by FVANCOP** [comment]
I check next week in the code if I could implement your (good) request.

François

**Comment by FVANCOP** [comment]
Unfortunately, I don't see how to implement your request in the code of ChartNew.js; The function that computes the size of the Yaxis can not be called from your program... and this function computes other values that would provide other results if the canvas is resized... (I hope those explanations are comprehensive).

The only solution that I can propose is to change the width (height) of the canvas before you call the chart function. See new file "Samples\resize_canvas.html".

**Comment by gavinspearhead** [comment]
Thanx for taking the time to look into this. I'm not sure we are actually talking about the same thing. I now end up with something that looks like this.

![old](https://cloud.githubusercontent.com/assets/5463588/9673186/e7a40976-52a1-11e5-8767-4a96f3832bae.png)

And this is what I would like to end up with: (q&d drawing)

![new](https://cloud.githubusercontent.com/assets/5463588/9673185/e7881734-52a1-11e5-845a-907c2e758376.png)

The canvas size I create is generated dynamically from the size of the web page (and there are more than one on the same page) so apart from that it becomes complex (e.g. the size of the x-axis is generated from a dataset as well) to adjust the width of the canvas, I don't think it actually improves the way it looks.

**Comment by FVANCOP** [comment]
I thought that you would also that the X axis was reduced to a smaller width; What you propose here can be implemented easely (I think); I try to implement it next week.

**Comment by FVANCOP** [comment]
option maxBarWidth has been created; Default value is -1 <=> no maximum for the bar width;

Specify the maximum bar width in point : 

Example : maxBarWidth : 50

See : https://github.com/FVANCOP/ChartNew.js/wiki/100_070_Graph_Layout#maxbarwidth

**Comment by gavinspearhead** [comment]
Works like a charm. Thanx a lot!
