### ISSUE TITLE
Add html into inGraphDataTmpl

### ISSUE THREAD

**Issue by ticidesign** [FVANCOP/ChartNew.js#346]
Is there a way to add an image html tag at inGraphDataTmpl?

**Comment by FVANCOP** [comment]
I'm currently busy with the developpement of a new add-ins ; With this new add-ins, it is something that will be possible. Still a couple of days before a definitive version ot the new add-ins is available.

**Comment by FVANCOP** [comment]
Samples can be found in the new published version:

see : Samples\Personal_*.html

**Comment by ticidesign** [comment]
what I need is more like this
![screen shot 2015-09-09 at 3 16 20 pm](https://cloud.githubusercontent.com/assets/289889/9753881/e14168e0-5705-11e5-9c62-4351ab712f02.png)

So far I got this:
![screen shot 2015-09-09 at 3 17 45 pm](https://cloud.githubusercontent.com/assets/289889/9753884/f89b2eb8-5705-11e5-9740-822abb58bbbe.png)

**Comment by FVANCOP** [comment]
It's a challenge but I'm pretty sure that this could be created with ChartNew.js.

I come back with a solution in a couple of days.

**Comment by FVANCOP** [comment]
Hi,

In the Samples folder, you will find the "shapesInChart_for_issue346.html" that produces this : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/9831686/ec9af7b2-5960-11e5-9479-f5a2a2054561.png)

The code is not simple but you give me some ideas : in the next weeks, I will develop a new add-ins that will integrate this (and much more) with simple code.

**Comment by FVANCOP** [comment]
As promized, a new add-ins has been developped; It is more easy to produce it now.

The code has been updated to allow parameter "expandInRadius" and "expandOutRadius".

See (new version) : Samples\shapesInChart_for_issue346.html

![canvas2](https://cloud.githubusercontent.com/assets/6121933/11045235/8515f166-8726-11e5-94bb-81e113cec3ba.png)

Documentation : https://github.com/FVANCOP/ChartNew.js/wiki/900_070_SpecialInChartData.js

For expandInRadius and expandOutRadius see https://github.com/FVANCOP/ChartNew.js/wiki/070_030_Pie
