### ISSUE TITLE
Different error bars for each point in a line graph

### ISSUE THREAD

**Issue by samjjackson** [FVANCOP/ChartNew.js#349]
Hi There,

Further to my previous request (Issue #343) I was wondering if a similar output is possible using line graphs - ie I would like each point on a line graph to have a unique sized error bar, for example on this graph: http://www.samjj.net/sam1.html .

Thanks again for your work and support with this excellent script,

Sam

**Comment by FVANCOP** [comment]
Some updates in the code are necessary... But I think that it will be possible after that.

Another solution should be to use the shapesInChart.js new Add-ins, but it will be more complicate.

I come back soon with a solution.

**Comment by FVANCOP** [comment]
Download the last version and check Samples\math3.html

Result of the sample:

![canvas](https://cloud.githubusercontent.com/assets/6121933/9616074/76c80712-50fc-11e5-8a26-3f4998b0945e.png)

**Comment by meersonv** [comment]
It seems, that after last change in ChartNew.js number of samples stopped to work (for example, personal_inChartData_Bar.html, add-ins_format.html ...)
Error "ReferenceError: mathValueHeightVal is not defined" appears

**Comment by FVANCOP** [comment]
Oups - Yes; The last change was not 100 % correct; Problem has been fixed.

@meersonv : thanks for reporting the problem !!!!!!

**Comment by samjjackson** [comment]
Thanks again for help with this. Do I need to update the ChartNew files on my server to make these changes? Will that affect the pages I have already made? Thanks!

**Comment by FVANCOP** [comment]
Yes, you have to replace the ChartNew.js file and also the mathFunctions.js; This will not affect your current charts - Code has been changed in order to integrate a new possibilities.

Attention : be sure to download the very last version - see 2 messages here before :-(

**Comment by samjjackson** [comment]
I have done this, and I cannot get the sample.html example to work when viewing in the extracted ChartNew.js-master folder, so must have done something wrong with the upload. The html page title is there and the canvasses 'draw' (ie there is space for them on the page) but the charts do not appear. Will check my filenames/paths etc, but can you think of a reason why this would happen?

**Comment by FVANCOP** [comment]
I have retested the sample math3.html and it works fine on IExlorer/Firefox/Google Chrome.

Try to redownload the version...
