### ISSUE TITLE
scaleOverride2 & annotateLabel Double Axis

### ISSUE THREAD

**Issue by ulysnep** [FVANCOP/ChartNew.js#353]
Hello again!

I'm have a couple challenges: 
- Every time I use "scaleOverride2: true" on my bar and line graph, it breaks the graph and the graph doesn't show. I've been referencing: https://github.com/FVANCOP/ChartNew.js/wiki/100_035_DoubleAxis
- Is there a special way to reference "annotateLabel" when you have both a bar and line graph with different axis? Nothing seems to display regardless of what I put in annotateLabel.

Thanks in advanced!

**Comment by FVANCOP** [comment]
Can you send your code to my email address ? I will check.

**Comment by FVANCOP** [comment]
@ulysnep - Code received and analysed ! 

If you use scaleOverride2, you should also specify scaleStartValue2, scaleSteps2 and scaleStepWidth2.

**Comment by ulysnep** [comment]
Thanks again!
