### ISSUE TITLE
[Question] StackedBar with line

### ISSUE THREAD

**Issue by fabiomig** [FVANCOP/ChartNew.js#354]
Hi, everyone!

i want to create a graph like this one:
![4667736822120448](https://cloud.githubusercontent.com/assets/8770466/9785637/b629b3fa-57ab-11e5-8b46-6a703e3a6d46.png)

Is it possible with ChartNew?

Cheers

**Comment by fabiomig** [comment]
This is what i've achieved with ChartNew so far:

![5838131650625536](https://cloud.githubusercontent.com/assets/8770466/9785675/02dc3632-57ac-11e5-867d-7a74f1cfea2e.png)

**Comment by FVANCOP** [comment]
Hi,

In current version, lines can only be integrated in Bar charts not in StackedBar charts.

But I don't thing that it will be difficult to change the code to allow lines in StackedBar Charts.

I hope that I can deliver a version that integrates lines in stakedBar charts next week.

Francois

**Comment by fabiomig** [comment]
HI Francois.
Thanks alot for the awnswer.
I think this could benefit many people. If you could do it or perhaps give me some tips on how should be done, i think i could help you.

Cheers

**Comment by FVANCOP** [comment]
Download the last version and check Samples\StackedBar_with_line.html

Result of this sample : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/9887427/e5c1c506-5bef-11e5-9398-98b2d434d9b6.png)

**Comment by fabiomig** [comment]
Very cool. Thanks :+1:
