### ISSUE TITLE
[ISSUE] dots on right side

### ISSUE THREAD

**Issue by fabiomig** [FVANCOP/ChartNew.js#355]
I'm seeing this dots on right side of the graph
Am i missing something?

![5458422584573952](https://cloud.githubusercontent.com/assets/8770466/9787275/485b14aa-57b9-11e5-83ff-8b8bfb5e6c83.png)

**Comment by FVANCOP** [comment]
Hi Fabio,

Can you send the code to my email address ?

Thanks,
François
