### ISSUE TITLE
Error annotation label position

### ISSUE THREAD

**Issue by FerGabPereira** [FVANCOP/ChartNew.js#356]
sorry for my english:

When i use the option xPos sometimes the annotation label moves to the right.

in the example function_sinus_cosinus.html happens.

![bug](https://cloud.githubusercontent.com/assets/14280295/9857802/32a8c7fa-5af3-11e5-92a5-a59268feb896.png)

Thanks. Fernando

**Comment by FVANCOP** [comment]
To  be displayed, the annotation has not to be exactly on the point, but in the area of the point. By default, the annotate is displayed if the distance between the point and the mouse pointer is less than 10 points. You can reduce this default value by changing option "pointHitDetectionRadius", For instance, for the sinus_cosinus function, a value of 3 gives a better result..

**Comment by FerGabPereira** [comment]
Ty man :3
