### ISSUE TITLE
Annotate display issue on bar chart

### ISSUE THREAD

**Issue by leesuit** [FVANCOP/ChartNew.js#358]
I have a problem with displaying annotate on really small bars. Odd thing is that I can display them on zeroed bars but on small ones not. I attached sample picture. Blue and yellow ones working fine but red one no. Any clues? pointHitDetectionRadius option is for line and radar charts only.
![annotateissue](https://cloud.githubusercontent.com/assets/13274639/9932854/69773e64-5d47-11e5-888a-17a927d902c7.png)

**Comment by FVANCOP** [comment]
Can you send your code to my email address ? I will check what happens!

Thanks,
Francois

**Comment by FVANCOP** [comment]
Thanks for the code. I could resolve it by adding a new option  : annotateBarMinimumDetectionHeight. Default value is 0 and behavior will be the same as what you have now. Set it to 10 and you will have no problem to display annotations on zero values. 

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_020_Annotations#annotatebarminimumdetectionheight

**Comment by leesuit** [comment]
Perfect! Thanks!
