### ISSUE TITLE
shapesInChart output displayed on html but cannot exported as pdf.

### ISSUE THREAD

**Issue by Kosmas** [FVANCOP/ChartNew.js#359]
I've recently downloaded the shapesInChart.js add-in and used it to display an additional line in a bar chart.

The line is displayed on the html page, but when trying to export it with wkhtmltopdf, all the graphs are empty.

When the drawShapes is commented out, everything works as normal again.

**Comment by FVANCOP** [comment]
I really don't know how this work. The better that you can do is to open a problem on the wkhtmltopdg site.

Sorry for the late (and not really useful) answer.

**Comment by Kosmas** [comment]
No worries @FVANCOP. Thanks.
