### ISSUE TITLE
Background color only for Line chart, not for title,legend,..

### ISSUE THREAD

**Issue by Geoffry304** [FVANCOP/ChartNew.js#360]
Hey is it possible to get only a background color for the chart like in my example: https://jsfiddle.net/9eb8Lqx6/
This was made with Chart.js, but it has not so many options like ChartNew.Js

Thank you in advance,
Geoffry.

**Comment by FVANCOP** [comment]
Code has been updated to allow gradient colors for shapesInChart Add-ins.

See Sample : Samples/shapesInChart_gradientColors.html

The Add-ins "gradientColors.js" and "shapesInChart.js" have to be included in your code.
