### ISSUE TITLE
How to get which bar and its index I am hovering?

### ISSUE THREAD

**Issue by tom10271** [FVANCOP/ChartNew.js#365]
Supposedly I can bind event to canvas then I can get the bar I am hovering by: `var bars = chart.getBarsAtEvent(evt);` in original Chart.js. How to do it with ChartNew.js?

Besides, there is no way for developer to get the index of bar hovering, is it provided in ChartNew.js?

**Comment by FVANCOP** [comment]
Not sure that I understand what you want but check following : 

See Samples\mouse_detect_position.html (this is a new sample; You will have to redownload the last version of ChartNew.zip).
see also Samples\annotateFunction.html


Documentation associated : 
https://github.com/FVANCOP/ChartNew.js/wiki/100_020_Annotations#annotatefunctionin
https://github.com/FVANCOP/ChartNew.js/wiki/100_095_Mouse_Actions
