### ISSUE TITLE
Showing Label color(s) in Annotations

### ISSUE THREAD

**Issue by Bambicruz** [FVANCOP/ChartNew.js#367]
is there a way to show the color of the bar for each value like the legend (similar to what ChartJS offers for multitooltips), like the following:

multiTooltipTemplate: "<%if (label){%><%=datasetLabel%>: <%}%><%= '$' + value + ' billion' %>",

Thanks!

**Comment by FVANCOP** [comment]
I'm pretty sure, it is possible; but I have to find out how... I come back with the solution soon.

**Comment by Bambicruz** [comment]
Thank you! will await eagerly :)

**Comment by FVANCOP** [comment]
I got a solution, but there are some restrictions...

See Samples\bar_and_lines_with_detectAnnotateOnFullLine_with_box_legend.html

Restrictions : 
- option annotateRelocate cannot be set to true;
- if you use "rgba" colors for the "fillColor" (second canvas in the provided sample), the background color of the canvas must be white and the background color of the annotate must also be white.

If someone has a better solution, he is welcome :-)

**Comment by Bambicruz** [comment]
That'll do it, Thank you!
