### ISSUE TITLE
Double Axis different Labels

### ISSUE THREAD

**Issue by Bambicruz** [FVANCOP/ChartNew.js#368]
Can the Scales in double axis have different labels? For example:

Right Y Axis: Dollar amounts (scaleLabel: "<%='$'+value%>",)
Left Y Axis : Percentage (%) amounts (scaleLabel: "<%=value+'%'+%>",)

**Comment by FVANCOP** [comment]
Something like that should help : 

annotateLabel : "<%=(i==1 ? '$'+v3  : v3+'%')%>"

**Comment by Bambicruz** [comment]
Thanks. I was however, referring to the ScaleLabel. Can it be done?

**Comment by FVANCOP** [comment]
option scaleLabel2 also exists (for Lines and Bar charts) but was not working :-(

It has been fixed just now; Download the last published version.

Regards,
François

**Comment by Bambicruz** [comment]
Thank you Francois, that worked for the scale!

About the annotation, any idea how to replicate the same (the first value being in $, then the second in %)? I am using "annotateALLx" with the following code:

function annotateAllX(area,ctx,data,statData,posi,posj,othervars) {
	retstring=statData[posi][posj].v2+'<HR>';
	retstring=retstring+'';
	for(var i=0;i<data.datasets.length;i++){
		if(typeof statData[i][posj].datavalue!="undefined" && data.datasets[i].type != "Line")retstring=retstring+statData[i][posj].v1+" : "+" $ "+statData[i][posj].datavalue+"<br>";
	}
	return "<%='"+retstring+"'%>";
}

**Comment by FVANCOP** [comment]
Something like this : 

     function annotateAllX(area,ctx,data,statData,posi,posj,othervars) {
	     retstring='<B><U>'+statData[posi][posj].v2+'</U></B><BR>';
	     for(var i=data.datasets.length-1;i>=0;i--){
		     if(typeof statData[i][posj].datavalue!="undefined" && data.datasets[i].type != "Line"){
			     var boxLegend="<canvas id=\"canvas_Line"+posi+"_"+posj+"\" height=\"10\" width=\"30\" style=\"border:1px solid black; background : "+data.datasets[i].fillColor+"\"></canvas>";
			     if(data.datasets[i].axis==2)retstring=retstring+boxLegend+" "+statData[i][posj].v1+"="+statData[i][posj].datavalue+" %<BR>";
			     else retstring=retstring+boxLegend+" "+statData[i][posj].v1+"="+statData[i][posj].datavalue+" $<BR>";
		     }
	     }
	     return "<%='"+retstring+"'%>".replace(/<BR>/g," ");

     }

**Comment by Bambicruz** [comment]
Merci beaucoup!
