### ISSUE TITLE
Export Horizontal StackedBar chart to PDF

### ISSUE THREAD

**Issue by joy1979** [FVANCOP/ChartNew.js#378]
Hello,

I am trying to export the Chart to PDF. I see save to PNG option but I am not able to find Export to PDF in documentation. Do we have that functionality implemented to support the Chart export to PDF? If yes please advise the steps or any other way if I can achieve this functionality? Please let me know if you have any questions.

Thank you.
Joy1979

**Comment by FVANCOP** [comment]
Hi,

Nothing is foreseen in the code to export charts to PDF. What you can do, is export it to PNG and then print it to a Pdf format (in Windows, you probably have a "Pdf" printer defined by default).

Regards,
François

**Comment by webguy262** [comment]
François

I'm using chartNew in a phonegap app. Works great! But when I try to save the charts to PDF, almost always, only the axes appear; no bars show up.

The "almost always" has me puzzled... any thoughts why bars would appear occasionally, but usually not? Do the bars get painted in a 'second pass' thru your code? Might the app think the PDF has been created when only the axes are done? Love to hear your thoughts!

BTW, I'm using two plugins for saving PDFs -- iText & html2pdf -- and they are the most popular tools as far as I can tell. 

So unless you have a 'silver bullet' solution ; ), I'm thinking about making PNGs from the canvas charts, and then saving those to the PDF. Using CSS, I would hide the PNGs on "screens," but show them for "print" while hiding the canvases. A theory at least!

Have you seen any code that generates PNGs from chartnew canvas elements in the flow of the document? I've tried, but I get blank, transparent PNGs of the matching canvas size. I think my canvas.toDataURL() is firing before the canvas is painted? 

I'm doing 

```
<img src="" id="canvasImg">
<script>
var img = document.getElementById('canvasImg');
img.onload = function(){
	var canvas = document.getElementById('canvas_gest_va');
	var dataURL = canvas.toDataURL();
	alert(dataURL);
	document.getElementById('canvasImg').src = dataURL;
};
</script>
```

Thoughts?`

**Comment by FVANCOP** [comment]
Last question has been reported to issue #434
