### ISSUE TITLE
Chart containing only vertical lines (Is this possible?)

### ISSUE THREAD

**Issue by bioinf-ice** [FVANCOP/ChartNew.js#379]
I want to draw a line chart similar to this on:
https://www.broadinstitute.org/files/shared/proteomics/ms.jpg

(The numbers above the lines are not that important at the moment.)

Is this possible with the current version of ChartNew.js? I searched the examples and documentationalready , but couldn't find an answer.

Thanks.

**Comment by FVANCOP** [comment]
Good idea and not too difficult to implement. ChartNew.js has been updated to allow such a chart.

Option "linkType" has been defined; For your request, you have to specify "linkType : 1".

Download the last version and see Samples\linkType.html

I will document it in the coming days (and probably perform other improments in the code).

Regards,
François

**Comment by bioinf-ice** [comment]
Looks great!

Thanks a lot for adding this feature. It's exactly what I was looking for.
