### ISSUE TITLE
Same line as drawXScaleLine from Line chart in other graph types?

### ISSUE THREAD

**Issue by markosko** [FVANCOP/ChartNew.js#381]
Is there any other way to draw line in other graph types like drawXScaleLine from Line type chart, for example Horizontal Stacked Bar graph?
![image](https://cloud.githubusercontent.com/assets/7886449/10846532/a36cbde8-7f10-11e5-82cc-cb3d0a5024f6.png)

code for drawn line
```javascript
var benchmark=50;
mydata1.shapesInChart=[];
mydata1.shapesInChart[0] = {
	position : "inchart",
	shape: "line",
	x1: benchmark,
	y1:  -0.5,
	x2:  benchmark,
	y2:  0.5+mydata1.datasets[0].data.length-1,
	strokeSize :4,
	strokeColor:"red",
	iter : "last"
}
```

**Comment by FVANCOP** [comment]
Hi,

Using the shapesInChart technique is the only option to draw lines in charts... drawXScaleLine is an exception for Line chart. Perhaps in the (near) future, I will allow lines in combination with all chart types... I have to think about but I'm buzy with other developments.

Thanks for your answer in issue #382. it was perfect; I will not add an option for the request in this issue. It is too specific. One will have a request with 3 or more colors; another will have other requests associated to it;  It will never ends; Functions are available and make it power enough (I think).

Regards,
François

**Comment by FVANCOP** [comment]
I forgot to mention that for (vertical) Bar and HorizontalBar you can mix bars and lines. See Samples/bar_and_lines_with_detectAnnotateOnFullLine.html. But this is not allowed for HorizontalBar and HorizontalStackedBar.

Documentation can be found in https://github.com/FVANCOP/ChartNew.js/wiki/070_020_Bar

**Comment by markosko** [comment]
Yeah, I was working on horizontal graphs and i was in need to set single line which would act as border between good and bad results. And now as i am looking at graph it's little bad example for that thing but main issue was that scale line though graph.

Thanks
