### ISSUE TITLE
HorizontalBar - Scale Start Override vs Values

### ISSUE THREAD

**Issue by ryock2000** [FVANCOP/ChartNew.js#392]
Hi,

if you override the scale start to a negative value, and if you don't have any negative value, all bars start from the override start instead of 0.

![image](https://cloud.githubusercontent.com/assets/16045559/11439626/bcd1f5b2-94ca-11e5-9095-a1c529451785.png)

![image](https://cloud.githubusercontent.com/assets/16045559/11439667/faff8476-94ca-11e5-963a-0e768733b190.png)

is there an option I forgot to set on my side ?

have a nice day

**Comment by FVANCOP** [comment]
It's a bug :-)

I will check how to solve it in the next days.

**Comment by markosko** [comment]
maybe this will help, change this
```javascript
	var zeroY = 0;
	if (valueBounds.minValue < 0) {
		zeroY = calculateOffset(config.logarithmic, 0, calculatedScale, valueHop);
	}

```
to this in code 
```javascript
			var zeroY = 0;
			if (valueBounds.minValue < 0) {
				zeroY = calculateOffset(config.logarithmic, 0, calculatedScale, valueHop);
			}
			else if (valueBounds.minValue > config.scaleStartValue) {
				zeroY = calculateOffset(config.logarithmic, 0, calculatedScale, valueHop);
			}
```
after change it looks like this 
![image](https://cloud.githubusercontent.com/assets/7886449/11441104/0b1a4f88-9509-11e5-8c61-b5387be3a7a4.png)

not sure if this will lead to other bugs or something

**Comment by ryock2000** [comment]
Hi,

it has fixed the problem on my side.

I don't see other problem cause by the fix for now. But now I know where to look.

Thank you

**Comment by FVANCOP** [comment]
Code has been updated to fix the issue

Great thanks to @markosko for the debugging.

In fact, the zeroY value has to be computed without any condition and the bug was for Bar/StackedBar/Lines/HorizontalBar/HorizontalStackedBar.

**Comment by markosko** [comment]
Yeah, later i found that there was conditional useless, but probably no one till now checked this or used permanent negative start scale with positive numbers ? Not sure. And no problem.
