### ISSUE TITLE
multiple Tooltip for radar

### ISSUE THREAD

**Issue by CPASimUSante** [FVANCOP/ChartNew.js#406]
i saw [that issue](https://github.com/FVANCOP/ChartNew.js/issues/361) that made me think everything is possible, but i can't manage to adapt the principle for radar  chart.
I would like the same rendering as [radar for Chart.js](http://www.chartjs.org/docs/#radar-chart-example-usage) : having a unique tolltip for each label value and displaying the results for all datasets for that value (possibly followed by the dataset title). Something like : 

**Eating**
- [color of dataset1] 65 My First dataset
- [color of dataset2] 28 My Second dataset

Thank you

**Comment by markosko** [comment]
Hello,
try this copied from bar_and_lines_with_detectAnnotateOnFullLine_with_box_legend.html in Samples and little edited as u wrote in your issue
```javascript
//function for creating custom tooltip for datasets
function annotateAllX(area,ctx,data,statData,posi,posj,othervars) {
	retstring='<B><U>'+statData[posi][posj].v2+'</U></B><BR>';
	for(var i=data.datasets.length-1;i>=0;i--){
			var boxLegend="<canvas id=\"canvas_Line"+posi+"_"+posj+"\" height=\"10\" width=\"30\" style=\"border:1px solid black; background : "+data.datasets[i].fillColor+"\"></canvas>";
			retstring=retstring+boxLegend+" "+statData[i][posj].datavalue+" "+statData[i][posj].v1+"<BR>";
	}
	return "<%='"+retstring+"'%>".replace(/<BR>/g," ");

}

var opt1 = {
      canvasBorders : true,
      canvasBordersWidth : 3,
      canvasBordersColor : "black",
      legend : true,
      inGraphDataShow : true,
      annotateDisplay : true,
      annotateLabel: annotateAllX,

}
```

**Comment by CPASimUSante** [comment]
Works great, thanks ! i should have check in depth for doc
