### ISSUE TITLE
bower integration

### ISSUE THREAD

**Issue by foxreymann** [FVANCOP/ChartNew.js#408]
As a developer I would like to install ChartNew.js using bower package manager.

**Comment by FVANCOP** [comment]
No problem, but I have no experience in things like this. I suppose that I have to create a file with specific informations. 

Can you send (to my mail address) a clear description of what I have to do ?

Thanks,
François

**Comment by jxm262** [comment]
@FVANCOP  I'd also like to see this on bower.  It's fairly similar to npm which I see you've already done :)  

Here's an example to get you started - 
```
{
  "name": "x",
  "version": "x",
  "description": "",
  "homepage": "github link",
  "author": "",
  "main": [
     "ChartNew.js"   <-- note this is the entry point of the app
  ],
  "dependencies": {
    "chartjs": ">= 1.0.1-beta.4"   <-- or whatever version this depends on
  },
  "keywords": [
     ....
  ]
}
```

You can look here for how to register the package with Bower - https://bower.io/docs/creating-packages/

**Comment by FVANCOP** [comment]
Hi,

Following bower.json file has been created : 

       {
         "name": "ChartNew.js",
         "version": "0.3.0",
         "description": "Simple HTML5 Charts using the canvas element",
         "keywords": ["charts"],
         "homepage": "https://github.com/FVANCOP/ChartNew.js",
         "author": "FVANCOP",
         "license": "MIT",
         "main": ["ChartNew.js"],
         "dependencies": {
         }
       }

Registration has been performed, but not sure it is 100% correct. Can you try ?

       D:\Mes Programmes\HTML\KB>bower register ChartNew.js git://github.com/FVANCOP/ChartNew.js
       bower resolve       git://github.com/FVANCOP/ChartNew.js.git#*
       bower checkout      ChartNew.js#master
       bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
       bower resolved      git://github.com/FVANCOP/ChartNew.js.git#03d40808c5
       ? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
       bower register      git://github.com/FVANCOP/ChartNew.js
       Package ChartNew.js registered successfully!
       All valid semver tags on git://github.com/FVANCOP/ChartNew.js will be available as versions.
       To publish a new version, just release a valid semver tag.
       
       Run bower info ChartNew.js to list the available versions.

       D:\Mes Programmes\HTML\KB>bower info ChartNew.js
       bower not-cached    https://github.com/FVANCOP/ChartNew.js.git#*
       bower resolve       https://github.com/FVANCOP/ChartNew.js.git#*
       bower checkout      ChartNew.js#master
       bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
       bower resolved      https://github.com/FVANCOP/ChartNew.js.git#03d40808c5
       
       {
         name: 'ChartNew.js',
         description: 'Simple HTML5 Charts using the canvas element',
         keywords: [
           'charts'
         ],
         homepage: 'https://github.com/FVANCOP/ChartNew.js',
         author: 'FVANCOP',
         license: 'MIT',
         main: [
           'ChartNew.js'
         ],
         dependencies: {}
       }

       No versions available.

**Comment by FVANCOP** [comment]
Unfortunately, no news....

**Comment by foxreymann** [comment]
@FVANCOP Thank you, it is working. I've finished the project long time ago so I've forgot about the issue but it is working:)
