### ISSUE TITLE
getSegmentsAtEvent is not available

### ISSUE THREAD

**Issue by ahmadalyan** [FVANCOP/ChartNew.js#409]
Hi Dear 

I am trying to add click function on my Chart but I missed getSegmentsAtEvent function which is available in Chart.js 

is there any other solution where I could attached click function to my Doughnut chart

**Comment by markosko** [comment]
What is function getSegmentsAtEvent? u want get which segment u clicked on? If yea mouse events / functions have parameter other which gives information about part of graph clicked on

**Comment by ahmadalyan** [comment]
where I could find more info about mouse events

**Comment by markosko** [comment]
try check this page https://github.com/FVANCOP/ChartNew.js/wiki/100_095_Mouse_Actions
If u need some more detailed info i think u can write mail to and @FVANCOP so we wont spam here too much

**Comment by ahmadalyan** [comment]
thanks a lot :)
