### ISSUE TITLE
responsive Chart: canvas streched after resize

### ISSUE THREAD

**Issue by henrythasler** [FVANCOP/ChartNew.js#414]
When resizing the browser window with a responsive chart (chartOption `responsive=true`) the resulting html is as follows:
`<canvas id="canvas" width="1054" height="632" style="width: 971px; height: 582ps"></canvas>`
The style-dimension differ from the canvas-dimensions resulting in an stretched and blurred chart.
### Proposal:

Do not set a canvas dimensions in style attribute.
In Chartnew.js:
`window.Chart = function(context) {`
`(...)`
`if (window.devicePixelRatio) {`
`context.canvas.style.width = width + "px";`    **<-- remove this line**
`context.canvas.style.height = height + "px";`      **<-- remove this line**
`context.canvas.height = height * window.devicePixelRatio;`
`context.canvas.width = width * window.devicePixelRatio;`
`context.scale(window.devicePixelRatio, window.devicePixelRatio);`

**Comment by FVANCOP** [comment]
Thanks for your suggestion but If I remove those two lines, there are problems on IOS... So, I hope that you will understand that I will not remove them.

Regards,
François

**Comment by rajesh-kanna** [comment]
Hi @FVANCOP : U have any solution for this! Because if i resize the window the chart is getting blurred lot.

**Comment by FVANCOP** [comment]
Can you try the version located in the new created branch ? I think that it will solve the problem but not 100 % sure.

https://github.com/FVANCOP/ChartNew.js/tree/fix-issue-414

Regards,
Francois

**Comment by markosko** [comment]
Hello,
looks better now at least in chrome and firefox :) Dont know what IE but in
IE8 script die on calling Chart function

Marek

2016-03-24 22:55 GMT+01:00 Francois Vancoppenolle <notifications@github.com>
:

**Comment by FVANCOP** [comment]
Apparently, changing the size of the canvas is not allowed in IE 8. Code has been updated to avoid problems with IE 8 when option responsive is set to true.

Can you retry the code of the branch ?

https://github.com/FVANCOP/ChartNew.js/tree/fix-issue-414

Thanks for testing :-)

**Comment by markosko** [comment]
Probably problem is with dynamic creating of canvas element and IE8 dont have support for getContext so it gives error but after doing something like in link(below) it work but probably canvas not resizing but nor stretching so i think thats not that much issue now  
http://stackoverflow.com/questions/10101372/excanvas-js-is-not-working-in-ie8?answertab=votes#tab-top

**Comment by FVANCOP** [comment]
A new version has been published today. I hope that it fixes this issue :-)

Problem with IE8 (see Markosko answers) has also been fixed (option responsive not available on IE8).
