### ISSUE TITLE
updateChart fails to update the entire dataset

### ISSUE THREAD

**Issue by MaxEvron** [FVANCOP/ChartNew.js#415]
Hey,

I use a page where users can select a report and set some parameters to retrieve associated data. When I retrieve the data for the very first time since the page is loaded, I call the following:

`new Chart(document.getElementById("mycanvas").getContext("2d")).Line(data, options));`

If the user choose another report or set others parameters, then when I retrieve other data, I call the following :

`updateChart(document.getElementById("mycanvas").getContext("2d"), data, options, true, true);`

My options are as follow:

```
var options = {
        responsive : true,
        animationByDataset : true,
        animationLeftToRight : true,
        legend : true,
        inGraphDataShow : true,
        inGraphDataAlign : "center",
        inGraphDataPaddingY : 15,
        inGraphDataPaddingX : 0,
        inGraphDataFontStyle : "bold",
        highLight: true,
        mouseMove: chartMouseFocus,
        mouseOut: chartMouseBlur
}
```
With `chartMouseFocus` and `chartMouseBlur` some personal functions to highlight data in an isolated html `<table>`.

On the screen, the chart is redrawn the right way and highlight works fine when retrieving data for the very first time. But, after retrieving new data and calling `updateChart`, even if the chart is redrawn the right way, hovering the chart suddenly replaces the freshly redrawn chart with the one created from the data loaded the very first time.

Thus, it seems updateChart does not do all the job.

**Comment by FVANCOP** [comment]
I think that you have the same problem that I found with the drillDown.js add-ins used in association with the highLight feature. 

One think that you can try, is to put a call to "deleteHighLight(ctx,data);" just before the update function.

If it does not work, can you send your code **to my email address** so that I can try to debug the problem and find a solution.

Regards,
François

**Comment by MaxEvron** [comment]
Thanks François. Could you please tell me what is `data`, here? Is this the previous or the new data?

**Comment by FVANCOP** [comment]
For safety, you can do it for both data; But please, take contact by mail for subsequent questions about that problem; Otherwise, followers receive lot of mails they are not interested in.

**Comment by MaxEvron** [comment]
Hey François,

Thank you for answering. Don't know if you speak French. If so, I do too.
You can answer in French. :)

So, I tried the deleteHighLight code you suggested but this does not
address the issue. When hovering the data after the highlight option is
turned to true, it works fine the first time the data collection is loaded
but displays a chart for the very first data collection if the chart is
updated with new a new data collection. Calling deleteHighLight twice with
both previous and new data collections has no effect.

Here are extracts of the code :

var objLastData = null;

var objChartOptions = {
    responsive : true,
    animationByDataset : true,
    animationLeftToRight : true,
    legend : true,
    inGraphDataShow : true,
    inGraphDataAlign : "center",
    inGraphDataPaddingY : 15,
    inGraphDataPaddingX : 0,
    inGraphDataFontStyle : "bold",
    highLight: true, /* Bug in chartNew: updated data not taken into
account when hovering */
    mouseMove: chartMouseFocus,
    mouseOut: chartMouseBlur
}


if (objLastData == null) {
    objLastData = data;
    new Chart(document.getElementById("chart").getContext("2d")).Line(data,
$.extend({}, objChartOptions, {graphTitle : data.title}));
} else {
    deleteHighLight(document.getElementById("chart").getContext("2d"),objLastData);
    deleteHighLight(document.getElementById("chart").getContext("2d"),data);
    updateChart(document.getElementById("chart").getContext("2d"),
data, $.extend({}, objChartOptions, {graphTitle : data.title}), true,
true);
    objLastData = data;
}

Here are two samples of data :

{"title":"Donn\u00e9es de
d\u00e9veloppement","labels":["01-01-2015","01-04-2015","01-07-2015","01-10-2015"],"datasets":[{"title":"Entite
A","data":[49,12,57,3]},{"title":"Entite
B","data":[43,94,27,97]},{"title":"Entite
C","data":[5,98,26,10]},{"title":"Entite D","data":[19,57,19,90]}]}

{"title":"Donn\u00e9es de
d\u00e9veloppement","labels":["01-01-2015","01-04-2015","01-07-2015","01-10-2015"],"datasets":[{"title":"Entite
A","data":[28,32,32,58]},{"title":"Entite
B","data":[56,75,50,31]},{"title":"Entite
C","data":[95,50,41,84]},{"title":"Entite D","data":[6,4,98,77]}]}

Thanks for your support.

Cheers.

2016-02-18 21:29 GMT+01:00 Francois Vancoppenolle <notifications@github.com>
:

> For safety, you can do it for both data; But please, take contact by mail
> for subsequent questions about that problem; Otherwise, followers receive
> lot of mails they are not interested in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FVANCOP/ChartNew.js/issues/415#issuecomment-185902332>
> .
>



-- 
Maxime Marais

**Comment by FVANCOP** [comment]
Problem fixed with last published version.

Thanks to @MaxEvron for his help - He founds the root of the problem.
