### ISSUE TITLE
Additional Data for each datapoint

### ISSUE THREAD

**Issue by PtrBld** [FVANCOP/ChartNew.js#433]
Hi is it possible to put additional data in together with the real datapoints. I am thinking of passing the id of each data along with the corresponding data point. After that I could call a method on mouse click and load additional information (by the id) via for example an ajax call.

**Comment by markosko** [comment]
Not sure if u want to put mode data points or additional series of datas but you can put together with json from ajax response to data variable used in graph and refresh graph with function in ChartNew and for sure u can write mail to me and @FVANCOP and one us will help you. I helped in one of issue with this.

**Comment by FVANCOP** [comment]
Nothing received... I close the ticket
