### ISSUE TITLE
IE11 Doughnut data in the middle calculation error

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#435]
Hi,

In IE11 when i set :

x1=2  y1=2  textAlign: "center  textBaseLine: "middle"   position: "realtive"

The value in IE 11 is on the right side of the donut.

Do i need to calculate the middle and set x1,x2  each time the screen resizes ? 

In chrome the calculation works fine....

Thanks,
Arie.

**Comment by FVANCOP** [comment]
Sorry, but I cannot reproduce the problem; Can you test if you have the problem with Samples\original_sample.html

If you do not have the problem with the sample, it is probably something in your code that causes the problem. If you do not find the solution, can you send the code to my email address ?

Regards,
François

**Comment by AK1979** [comment]
Hi,

The problem is not with the chart new but in the CANVAS element in IE11.

I get the same error as described here :

http://stackoverflow.com/questions/31685899/textalign-property-in-html5-canvas-not-working-properly-in-ie-11

The text is on the right of the doughnut and doesn't get aligned.

any ideas ? 

Thanks,
Arie.

**Comment by AK1979** [comment]
Do i nedd to adjust the x1 y1 parameters ? 

if there is alignement so what does this parameters purpose ?

**Comment by AK1979** [comment]
Hi

Found this microsoft NOTE ==> https://support.microsoft.com/en-us/kb/3161707

Will keep you updated.

If there any work arounds please let me know ...

**Comment by AK1979** [comment]
The problem was with IE11.

for now i changed the canvas dir to LTR and it works fine.

thanks :)
