### ISSUE TITLE
human numbers

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#436]
Hi , 

Is there any option to display human friendly numbers ? 

10,000 =  10K   and so on ....

**Comment by FVANCOP** [comment]
Yes, this is not too difficult. You have to change the default value for the "format" option.

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_050_Format and https://github.com/FVANCOP/ChartNew.js/wiki/900_010_format.js

**Comment by AK1979** [comment]
I can see date / time / round format options but not the above format.

Which format changes to human numbers ?  10000 to 10K ,  1,000,000 to 1M and so on .. 

Thanks :)

**Comment by markosko** [comment]
Check this one from wiki page  https://github.com/FVANCOP/ChartNew.js/wiki/900_010_format.js#abreviatenumber
This should be what you are looking for.

**Comment by AK1979** [comment]
Hi ,

thanks a lot .

can i use the "fmtYLabel : "abbreviatenumber" in a dougnut ?

**Comment by AK1979** [comment]
Is it possible in Line charts to adjust the annotateLabel format to   "abbreviatenumber"  ?

**Comment by FVANCOP** [comment]
Hi,

FmtYLabel is an option only valid for chart with axis; No axis in Doughnut, so fmtYLabel cannot be used in doughnuts.

To use the "abbreviateNumber in the annotate, set option fmtV3 : "abbreviateNumber".

Regards,
François

**Comment by AK1979** [comment]
Thanks.

Used annotateFctIn
