### ISSUE TITLE
change legend text

### ISSUE THREAD

**Issue by zoaeu12** [FVANCOP/ChartNew.js#437]
hi!
i want change legend text
like this : 
(default legend text + data value)
![doughnut chart](https://cloud.githubusercontent.com/assets/14974087/15319924/9965afe4-1c68-11e6-8e01-764d8c8bd5da.png)

thank you!

**Comment by FVANCOP** [comment]
Hi,

The code of the add-ins "stats.js" has been updated to allow this. Download last version.

See : Samples\stats_with_variables.html 

Documentation : https://github.com/FVANCOP/ChartNew.js/wiki/900_020_statistics

Regards,
François

![canvas](https://cloud.githubusercontent.com/assets/6121933/15369620/b96f2b6e-1d33-11e6-8ce1-39ca290eb3db.png)

**Comment by zoaeu12** [comment]
works perfect thanks! @FVANCOP
