### ISSUE TITLE
Is it possible to make the gridlines stop at each of the point on the graph.

### ISSUE THREAD

**Issue by ShawnSantiago** [FVANCOP/ChartNew.js#440]
Hi I was wondering if its possible to make the gridlines stop at each of the point on the graph. Like the image below
![chart](https://cloud.githubusercontent.com/assets/6554630/15636802/0e036c1a-25d8-11e6-8e72-22bb2fd620bd.png)

**Comment by FVANCOP** [comment]
Yes, it is but not simple as specifying an option. You have to create a function that adds lines that are drawn through the "shapes In Chart" add-ins module. I'll try to create a sample this evening.

François

see : https://github.com/FVANCOP/ChartNew.js/wiki/900_050_Shapes-Text-Images_In_Chart

**Comment by FVANCOP** [comment]
The sample is available : see Samples\issue_440.html

![canvas](https://cloud.githubusercontent.com/assets/6121933/15680143/c43e162e-2754-11e6-9990-1e6e4e88bf7f.png)


![canvas](https://cloud.githubusercontent.com/assets/6121933/15680164/ddb61980-2754-11e6-85fe-cf3e4cc09e7a.png)

**Comment by ShawnSantiago** [comment]
Amazing thanks man! your a life saver!
