### ISSUE TITLE
Multi charts – canvas error on the bottom of the page.

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#441]
Hi, 
I’m using GRIDSTER  to present multi charts inside widgets.
https://github.com/dsmorse/gridster.js
http://gridster.net/

For every widget I’m setting a DIV with CANVAS(chart) + ID  .
All of the charts in the seen part of the screen works great but the charts in the lower screen ( the area I need to scroll down in order to see ) is not getting rendered .
I’m using responsive mode + providing  unique id for every canvas inside the GRIDSTER widget .

( I’m working on a fiddle to reproduce the error )

Any ideas ? 

Thanks,
Arie.

**Comment by markosko** [comment]
Hello,
not sure if this can be problem but u can try using option and see if it works
`
dynamicDisplay : false
`

**Comment by AK1979** [comment]
Hi

Set it to false and it works .

Thanks a lot !

debug it later and will update.

**Comment by markosko** [comment]
No problem :) Looks like library interfere with computing location of canvases that should show when in view :/ but if not problem when they are rendered immediately it should be ok

**Comment by FVANCOP** [comment]
Perhaps that the problem will be fixed with the last version (there were lot of variables not defined in the function that computes the position of the element in the chart).
