### ISSUE TITLE
completely hide scale (including x and y axis)

### ISSUE THREAD

**Issue by chiarishow** [FVANCOP/ChartNew.js#442]
Hi,

is there an option to completely hide the scale?

including x and y axis. 

Thanks

**Comment by markosko** [comment]
Hello,
probably you want these options:
```
xAxisBottom : false,
xAxisTop : false,
yAxisLeft : false,
yAxisRight : false
```
if something u can check documentation for them at https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#xaxisbottom

**Comment by chiarishow** [comment]
already tried but as you can see here:

https://jsfiddle.net/qLdkby03/

the scale is not completely hidden. There's a light grey y and x axes.

**Comment by markosko** [comment]
add option, it will set lines as transparent so it will looks like its not there
```
scaleLineColor:"rgba(0,0,0,0)"
```

**Comment by chiarishow** [comment]
great!

almost perfect, 

but as you can see here:

https://jsfiddle.net/qLdkby03/1/

y lines are not hidden...

**Comment by chiarishow** [comment]
for anyone with my same problem,

just add:

`scaleGridLineColor: "rgba(0,0,0,0)"`

and everything will hide. 

Thanks @markosko !!!

**Comment by markosko** [comment]
Didnt see that grid scale lines but u can use this one and if something better if yout mail to me so we  wont spam people, email can be found in my profile ;)
```
scaleGridLineColor:"rgba(0,0,0,0)",
```

**Comment by chiarishow** [comment]
we comment at the same time! 

anyway for me it's ok! 

I closed the issue.
