### ISSUE TITLE
IE9 blink highlight chart

### ISSUE THREAD

**Issue by zoaeu12** [FVANCOP/ChartNew.js#447]
hi!
In IE9 browser i used default highlight options but chart is blink
help me plz

**Comment by FVANCOP** [comment]
For HighLighting, the chart is redrawn each time the mouse moves; This could produce a blinking effect on slow computers but probably also on IE9. I have no solution for that problem; I would say that you should migrate to a more recent browser.

**Comment by zoaeu12** [comment]
oh. perfectly understand.
thank you for your reply.
