### ISSUE TITLE
Stackedbar display total Value

### ISSUE THREAD

**Issue by zoaeu12** [FVANCOP/ChartNew.js#448]
hi!
this is my stackedbar chart
![chart1](https://cloud.githubusercontent.com/assets/14974087/16554301/db42db4c-4208-11e6-9a1d-e7c96965a11f.png)

and i want display total value like this

![chart2](https://cloud.githubusercontent.com/assets/14974087/16554309/ec32f16c-4208-11e6-9cfc-a9c6db21f1b0.png)

it is possible?

**Comment by FVANCOP** [comment]
See new sample Samples\stackedBar_with_total.html

It uses the add-ins ShapesInChart.js

![canvas](https://cloud.githubusercontent.com/assets/6121933/16568926/652a9ca6-4230-11e6-90a0-46f8452fcf66.png)


Documentation : https://github.com/FVANCOP/ChartNew.js/wiki/900_050_Shapes-Text-Images_In_Chart

**Comment by zoaeu12** [comment]
pefect! exactly what i need!
thank you so much
