### ISSUE TITLE
underline graphTitle text

### ISSUE THREAD

**Issue by zoaeu12** [FVANCOP/ChartNew.js#452]
thanks for your awesome library.
how can i make underline graphTitle?

**Comment by FVANCOP** [comment]
Hi,

In current version, it is not possible, however, it is possible to draw a border around the title. see https://github.com/FVANCOP/ChartNew.js/wiki/100_130_Border_and_Background_Color-for-text.

I think that I will add an option to specify which lines of the border has to be drawn. This will make possible to underline a text zone... Probably available at the end of augustus.

**Comment by zoaeu12** [comment]
i added graphTitleUnderline options(width, color, padding ...) and used 'setTextBordersAndBackground' function. it work! thank you for reply. @FVANCOP

**Comment by zoaeu12** [comment]
i added Underline Options(width, color, padding ...)
and used 'setTextBordersAndBackground' function
code is : 
```
if(Underline){
    ctx.save();
    ctx.lineWidth = UnderlineWidth;
    ctx.strokeStyle = UnderlineColor;
    var textWidth = ctx.measureText(text).width;
    ctx.moveTo(0 - (textWidth / 2) + UnderlinePaddingX, UnderlinePaddingY);
    ctx.lineTo(textWidth - (textWidth / 2) + UnderlinePaddingX, UnderlinePaddingY);
    ctx.stroke();
    ctx.restore();
}
```

![test](https://cloud.githubusercontent.com/assets/14974087/17044335/290177cc-4ffa-11e6-8314-9b261af91a5f.png)

it is half success.. help me

**Comment by FVANCOP** [comment]
In the last version, new options have been added. To underline the title, set option graphTitleBordersSelection to 1.

See : https://github.com/FVANCOP/ChartNew.js/wiki/100_130_Border_and_Background_Color-for-text
