### ISSUE TITLE
Problem in parameter inGraphDataTmpl on new version of chartnew.js

### ISSUE THREAD

**Issue by pedrotvr** [FVANCOP/ChartNew.js#457]
Hey guys,

In the version 2 of chartnew i was using in my dou and pie charts this parameter on configuration to show a label inside of the chart.

inGraphDataTmpl : "<%=v1%>"

And now with the new version, mantaining the same code the label don't appear in the chart and if comment this line the label that appear is incorrect. 

Can someone find way to solve the problem? 

if you need prints, please say it.

Best Regards, 

Pedro.

**Comment by markosko** [comment]
Hello with version 3 there was change with assigned variables in templates so u need to check for new version, so for label it will be as v1 is now title of graph as its now matching to other graphs api/variables in templates

so simply its should be enough to change from v1 to v2 to get label back to graph
```javascript
inGraphDataTmpl : "<%=v2%>"
```
https://github.com/FVANCOP/ChartNew.js/wiki/120_Template_variables#piedoughnutpolararea

Other changes are written here 
https://github.com/FVANCOP/ChartNew.js/wiki/033_version_3

**Comment by pedrotvr** [comment]
okok. 

That was nice, changed "label" to "title" in chart dataset and worked well.

Thank you :dancer:
