### ISSUE TITLE
legendPosX=4 with maxLegendCols=1 is broken

### ISSUE THREAD

**Issue by eythort** [FVANCOP/ChartNew.js#458]
works as expected in version 2, but in version 3 the legends appear in one line (not one column) side of the canvas, pushing the chart to be almost zero width.

legendPosX=3 works the same way as in version 2

**Comment by FVANCOP** [comment]
Yes, it is a "bit" inconsistent, but when legendPosY is not 0 or 4 and legendPosX is 0 or 4, maxLegendCols is in fact the maximum number of ... lines. I have to rethink the name of this option. 

For your chart, if you remove option maxLegendCols, you should get a fine chart. Can you try to remove this option from your code ?

**Comment by eythort** [comment]
Removing the maxLegendCols from the options did the trick! It now appears as in v2. 
I agree it's a "bit" inconsistent. I'd either change the name of this option or add maxLegendRows, etc. At least change the documentation for the maxLegendCols for now :)

**Comment by FVANCOP** [comment]
option maxLegendLines has been defined and documentation updated.

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_090_Legend#maxlegendlines

thanks @eythort :-)
