### ISSUE TITLE
Scroll chart 

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#459]
Hi,

When a large data set is presented on a small width canvas you can't see the bars.

Is there any option to set horizontal scroll bar to the chart ?

**Comment by markosko** [comment]
Hello,
as chart is in canvas, and on its own it cannot have scrollbar, but workaround can be if u set div with overflow which will have inside canvas with charts and canvas will more width and div inside which is div will have smaller width dont think there is way to do it over canvas
