### ISSUE TITLE
setting more parameters

### ISSUE THREAD

**Issue by DaveC426913** [FVANCOP/ChartNew.js#46]
May be bugs or missing features, not sure.

1] When rendering a bar graph, fillColor and strokeColor seem to have no default, so that if you exclude them, it throws an error: Uncaught TypeError: Cannot read property '0' of undefined.

2] I don't find any way of wrapping the labels. Some of my Y-axis labels are very long, and it would be nice if I could wrap them to a second line. I don't think it's simply a matter of <br/>; I think it has to do with the canvas, so maybe you have to specify a box width of some sort so that it wraps within the box?

**Comment by cdp1987** [comment]
Is it possible to add a hyperlink to y axis labels?

**Comment by FVANCOP** [comment]
Hi,

It is not possible to add a hyperlink in graphs; If you need some actions when you click on the graph, you can use the mouse function "mouseDownLeft" (see https://github.com/FVANCOP/ChartNew.js/wiki/100_095_Mouse_Actions). Though the "event" parameter of this function, you get the mouse position but ... you don't know the y axis labels position.... I don't thing it will help to reach your purpose...

François

**Comment by cdp1987** [comment]
Hi François

Thank you very much for your quick reply. I thought this might be the case.
The mouse function as you have said is not really what I am after.

I may resort to coding this in d3 to get around the issue.

Once again your help and the extremely quick reply is appreciated.

Many thanks,
Chris

Chris Parmenter

*Interactive Developer*City A.M.

Tel: 020 3201 8979
3rd Floor, Fountain House, 130 Fenchurch Street, London EC3M 5DJ

*CONFIDENTIALITY NOTICE*
This e-mail transmission and any documents, files, or previous e-mail
messages appended or attached to it may contain information that is
confidential or legally privileged. If you are not the intended recipient,
or a person responsible for delivering it to the intended recipient, you
are hereby notified that you must not read this transmission and that any
disclosure, copying, printing, distribution, or use of the information
contained or attached to this transmission is STRICTLY PROHIBITED. If you
have received this transmission in error, please immediately notify the
sender by telephone or return e-mail message and delete the original
transmission, its attachments, and any copies without reading or saving in
any manner.
