### ISSUE TITLE
Bar chart with different colors

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#461]
Hi

Is it possible to create a bar chart with different colors for each column ? 

i saw the stackedBar chart example and it dosn't stand with the data structure of the bar chart...

**Comment by FVANCOP** [comment]
Check : https://github.com/FVANCOP/ChartNew.js/wiki/070_020_Bar
I suppose that the second sample in the document is what you want (You have to associate an array of colors to fillColor).

Unfortunately, the "legend" associated to such a chart is not correct. But I'm currently working on something that will solve the problem.

**Comment by AK1979** [comment]
Thanks !
