### ISSUE TITLE
Automatically computed x axis labels and interval for date /time periods?

### ISSUE THREAD

**Issue by mrg21** [FVANCOP/ChartNew.js#462]
Is it possible to automatically computed x axis labels and interval for date /time?
For data over a period, it would be useful if the x axis labels / begin / end / interval (year/month/week/day/hour...) would be created automatically for this period.

Would need this option, thank you.

**Comment by FVANCOP** [comment]
Automatic computation of x axis (time, integer, string, etc...) is not possible in ChartNew.js. It is only possible for the y-Axis.

In Samples/time_graph.html, you have a sample of a time chart.

Regards,
François

**Comment by mrg21** [comment]
Very sad, I wanted to switch from morris.js to ChartNew.js because it has beautiful charts and a lot more features. Did not thought that ChartNew.js can not do such simple things.
I have data of randomly distributed dates (usually quarter results), but there are always missing values, often over several years. In morris.js the x axis labels are created always correct by default, here is an example what kind of line chart I need:
http://jsbin.com/sokiwahozu/1/edit?js,output

**Comment by FVANCOP** [comment]
Not too difficult to produce this chart with ChartNew.js. I will try to send you the code during the week-end.

**Comment by thantoldo** [comment]
I'm also interested at this feature. Detecting time gaps is important at time series graphs. What about interpolating dummy points (x,0) in the graphs so that time gaps are displayed? Then, a gap detection algorithm out of a given time points is required.

**Comment by FVANCOP** [comment]
@mrg21  : Download the last version and check the Samples/date_chart.html; Hope I is what you want (the add-ins format.js has been updated to display quarters in format).

![canvas](https://cloud.githubusercontent.com/assets/6121933/18609144/1f13f982-7cfb-11e6-8fb1-5d2381b57a7a.png)

@thantoldo : One of the purpose of a chart is precisely to interpolate dummy points. An algorithm that fills in the gaps could be written, but it is out of the scope of this project. This should be part of a statistical project. Sorry for that.

**Comment by mrg21** [comment]
Thank you very much, that's a big help.

One suggestion I would have: It is possible to label the timeline period so that the labels are not be shown at the beginning, but in the center of the period (at the middle between the beginning and end)?

**Comment by FVANCOP** [comment]
Your request has a sense for time chart. I will try to implement something in the next version (I hope that I can deliver something at last in November).
Otherwise, it is possible to put text in chart (with the Add-Ins "shapesInChart.js" - https://github.com/FVANCOP/ChartNew.js/wiki/900_050_Shapes-Text-Images_In_Chart) but not easy to achieve a good result.

**Comment by FVANCOP** [comment]
download the last version and set option xAxisMiddle : true.

Samples/date_chart.html has been updated with this new option.

**Comment by mrg21** [comment]
Great, thank you.
