### ISSUE TITLE
Is it possible to create overlapping Bar Chart with several axes

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#464]
Is there an option to create charts, where there are two bars near each other that are overlapped by the third one?
![d0ygx](https://cloud.githubusercontent.com/assets/10071245/18635209/df31c09a-7e8c-11e6-8c36-d35982b74560.png)

thank you.

**Comment by FVANCOP** [comment]
Yes, but not so simple. You have to use the Add-ins/shapesInChart.html (see - https://github.com/FVANCOP/ChartNew.js/wiki/900_050_Shapes-Text-Images_In_Chart)

See new Samples/third_bar.html. 

![canvas](https://cloud.githubusercontent.com/assets/6121933/18646686/ec4debc0-7eb2-11e6-8c30-2162bded5b0b.png)

**Comment by luna2761** [comment]
Thank you for your response.
Looks great, however I wonder if it is possible to create such chart, when all 3 bars are taken from an array, not drawn. First 2 should respond to the left axis, and third overlapped to the right axis. Is it possible?

![untitled](https://cloud.githubusercontent.com/assets/10071245/18752878/6c9a37bc-80ec-11e6-8760-222d6c934921.png)

Thank you.

**Comment by FVANCOP** [comment]
Theoritically, it is not possible : shapes drawn with the "shapesInChart.js" add-ins always respond to the left axis.

However, if you fix yourself the values of the right and left axis (*), you could convert the value of the third bars to the scale of the first axis... It seems complicate to setup but I suppose that it should be possible.

(*) with options : scaleOverride, scaleStartValue, scaleStepWidth, scaleOverride2, scaleStartValue2 and scaleStepWidth2 (https://github.com/FVANCOP/ChartNew.js/wiki/100_030_Axis#scalesteps)

**Comment by luna2761** [comment]
Thank you,
Actually, I can just turn drawn axes vice versa).
One more question: is there property like inGraphDataShow for drawn shapes? And possibility to show y2 value in it.

Thank you once more.

**Comment by FVANCOP** [comment]
I have updated (completely changed) the code of  Samples\third_bar.html. In this new code, all your requirements (and even more) are met : 
- a bar over the other ones (even more than 2 bars if you want),
- the "over bars" is associated to the right axis; other bars are associated to the left axis;
- the value of the "over" bar is displayed on top of the bar (but you can put other text if you want).

BUT : to create it, I had to change a little bit the code; This new code is not yet the official version of ChartNew.js. Temporarely, you can access to this new code with following link : https://github.com/FVANCOP/ChartNew.js/tree/legend_addins

Result of the new "third_bar.html" : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/18994624/f1e98142-8728-11e6-89da-a32dae387e71.png)

**Comment by luna2761** [comment]
This is fantastic! Thank you very much!
Everything works great!

P.S. Small question: where can I manage distance between bars within one column (like here - distance between set of three bars)?

**Comment by luna2761** [comment]
Thank you very much! 
Will be waiting for new library release).
