### ISSUE TITLE
Align Title / Subtitle to the left

### ISSUE THREAD

**Issue by Bambicruz** [FVANCOP/ChartNew.js#469]
Seems like a fairly basic option but I cant align the Title / Subtitle to the left (instead of center). Any help?

Thanks!

**Comment by lokapal** [comment]
Just replace title/subtitle with CrossText. Fortunately we can do it unlike basic chart.js ;-)

**Comment by FVANCOP** [comment]
options have been added in the just published version. You can now align title, subtitle, footnote on the left or on the right.

see : https://github.com/FVANCOP/ChartNew.js/wiki/100_060_General_Layout#footnotealign, https://github.com/FVANCOP/ChartNew.js/wiki/100_060_General_Layout#graphsubtitlealign and https://github.com/FVANCOP/ChartNew.js/wiki/100_060_General_Layout#graphtitlealign .
