### ISSUE TITLE
Rescaling on re-draw (iOS)

### ISSUE THREAD

**Issue by michiel555** [FVANCOP/ChartNew.js#47]
Bug-report:
On iOS devices, when re-drawing on a previously used canvas, the newly rendered chart causes a significant width and height increase of the canvas. This scaling issue always arises when targeting a 'used' canvas, but never on a 'new' canvas.

Solution:
This bug can be circumvented by replacing the target DOM canvas element before drawing, for example with jQuery .replaceWith(). By using this, functionality is retained on all other platforms/browsers. 
Perhaps this single line of code, or another solution, could be included in a future release.

**Comment by FVANCOP** [comment]
Problem seems to be fixed but you need to use fonction updateChart to update the chart.

see #331 , #309 

Documentation for updateChart : https://github.com/FVANCOP/ChartNew.js/wiki/180_Update_Chart
