### ISSUE TITLE
Merge chart new to chart js 2.0 

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#472]
Hi

Not trying to be disrespectful or something BUT

Why don't you merge this library to chart js ? 

Chart js 2.0 is a strong library with many new features and also mega responsive.

What are the advantages of this library over chart js 2.0 ?

**Comment by markosko** [comment]
Hello,
as user of this library and little contributor too.
If you compare both source codes you will firgure out what's quite big problem of merging is that both libraries at this stage are at totally different code base so not much chance to merge them

**Comment by FVANCOP** [comment]
see https://github.com/chartjs/Chart.js/issues/356

**Comment by AK1979** [comment]
Hi
I’m following and using  this two projects and you have added  great features but the basics  such as responsiveness / scales / tooltips options are more professional in chart.js .
The above post is two years ago where there were no contributors and the traffic was low.
Take a look at chart 2.0 . There many changes and many contributors (180)  and I thing that now is a good time to consider merging  :)

**Comment by FVANCOP** [comment]
I agree 100 % with you that Chart.js is more professionel but I've really no time to merge ChartNew.js into Chart.js.... ChartNew.js has been developped because there was a lack of reactivity with Chart.js which is apparenlty no more the case. Merging both version is not an easy job....

**Comment by AK1979** [comment]
Hi
I’m going to map all of the features in this library and open a project request on chart 2.0 .
I think it would be a waste to not combine these two libraries.
Every feature that you’ve developed here would be more efficient in chart 2.0.
Anyhow, thanks for your effort.

**Comment by fulldecent** [comment]
@AK1979 Doing a feature comparison would be helpful and analysis, thank you!
