### ISSUE TITLE
Is there a way to display percentage instead of value using pushInGraphData

### ISSUE THREAD

**Issue by 69amandine** [FVANCOP/ChartNew.js#475]
Hi,
I'm working on a project where i had to use the pushInGraphData for my pie chart.
I have to display the percentage instead of the real value as this one is really long ... Is there a way to add Percent value next to the "Title" tag.  I tried using an in chart data template but it doesn't work ... 

Thank you !

Here's my sample code : 

pushInGraphData("Pie",data,pieOptions,{
text : "<Title>",
fontSize : 12,
linkStrokeColorLine : "#666666",
linkStrokeSizeLine : 1,
avoidOverwrite:true
});

**Comment by FVANCOP** [comment]
Hi,

Yes, it is possible and not difficult (be sure that you use a recent version of ChartNew.js - data structure for Pie Chart have been changed completely in June). 

As you find, you have to change the value of the template. 

Try one of the following : 
inGraphDataTmpl: "<%=v6 + ' %'%>"
inGraphDataTmpl: "<%=v6%>"

If you still have problems, send me a mail with your code and I will check what's wrong.

François

**Comment by 69amandine** [comment]
Thank you for the fast reply Francois !
I'm using the latest version of chartnew (which is really great so far !)
Part of my first message was removed by the formatting ... Your sample code doesn't seems to work but my previous message wasn't really clear.
I am using this template : shapesInChart_for_PieChartV2.html
and i'd like to display the percent value next to the label instead of the real value in the canvas.
As this the "pushInGraphData" which seems to handle this, i can't figure how to access to the percentage value (as the initial value of text is : "Title (Value)".
Thank you again !

**Comment by FVANCOP** [comment]
The add-ins "specialInChartData.js" has been updated to allow this. A sample can be found in Samples\issue_475.html.
