### ISSUE TITLE
Selectable Text from legend

### ISSUE THREAD

**Issue by melody0711** [FVANCOP/ChartNew.js#478]
Is it possible to select the text (labels) from the legend in a chart to copy it?

I didn't find somthing like this. 

Thanks in advance!

**Comment by FVANCOP** [comment]
Hi,

Text in canvas can not be selected. However, you can perform an action when you click on the text. In the Samples folder, take the clicktextwithmouse.html as example. In this example, if you click on a text (in the legend or another text), you will see a popup windows with several informations about the text. 

See also https://github.com/FVANCOP/ChartNew.js/wiki/100_095_Mouse_Actions 

Regards,
François

**Comment by melody0711** [comment]
Thanks fot the quick answer! 

Best regards, Melanie
