### ISSUE TITLE
Space between bars

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#487]
Hi, Francois!

Please, advice with the next issue: I can't avoid space between bars within one label. I've tried to use "spaceBetweenBar" option, however that didn't work for me.
![capture](https://cloud.githubusercontent.com/assets/10071245/21187115/824d070a-c21f-11e6-8347-754fa878bc2f.PNG)

Thank you.

**Comment by FVANCOP** [comment]
Hi,

Try to play with following 3 options : 
                barValueSpacing : 10, barDatasetSpacing : 0,  barStrokeWidth : 0

Regards,
François

**Comment by luna2761** [comment]
Thank you!
For me "barDatasetSpacing : 0" plus "barStrokeWidth : 0" worked as needed.
