### ISSUE TITLE
Different background color in canvas in connection with label

### ISSUE THREAD

**Issue by luna2761** [FVANCOP/ChartNew.js#488]
Hello, Francois!

Again, that's not an issue, however I wonder if it is possible to have different backgrounds in canvas? 
For example, for (within) some labels - one color, for some labels - another.

Thank you in advance.

**Comment by FVANCOP** [comment]
Hello,

If you mean the color of the inGraphData, the option inGraphDataFontColor can be associated to a function (like lot of other options).

something like this : 

function setFontColor(area,ctx,data,statdata,i,j,othervars)
{
    if(i==0)return("red");
    else return("blue");	
}


inGraphDataFontColor : setFontColor,

**Comment by luna2761** [comment]
Hi again,

No, what I mean is background color - canvasBackgroundColor, but different for different labels.

Here is the picture, I think it explains better than I do))
![untitled](https://cloud.githubusercontent.com/assets/10071245/21356898/edd45db4-c6db-11e6-8a16-a578c290c012.png)

**Comment by FVANCOP** [comment]
It should be possible - I will send you a sample in a couple of day.

**Comment by FVANCOP** [comment]
Hi,

Download the last version (module Add-ins/shapesInChart.js has been changed) and check new sample Samples/highLight5.html.

Regards,
François

PS : wiki documentation will be updated soon.

**Comment by luna2761** [comment]
Hi,

I've checked the example https://github.com/FVANCOP/ChartNew.js/blob/master/Samples/highLight5.html,
however I see, that canvas background is always white. Is this correct path?

**Comment by FVANCOP** [comment]
Hi,

Have you also downloaded the new Add-ins/shapesInChart.js module ?

Following link is working fine for me : 

http://fvancop.github.io/ChartNew.js/Samples/highLight5.html

![canvas](https://cloud.githubusercontent.com/assets/6121933/21479502/4491ddd4-cb55-11e6-830f-0f2f7667ede0.png)

**Comment by luna2761** [comment]
This is what I see when I open the link http://fvancop.github.io/ChartNew.js/Samples/highLight5.html:
![lnk](https://cloud.githubusercontent.com/assets/10071245/21482289/abee0938-cb7a-11e6-83fe-1b9e70e87610.PNG)

The same when I've downloaded the new Add-ins/shapesInChart.js and used highLight5.html:

**Comment by FVANCOP** [comment]
I think that (again) I misunderstand your request. You want it for each group of rectangle, not when the mouse is hovering a rectangle.... In the sample that I provided, a background rectangle appears when the mouse is hovering a rectangle.

You need something similar to http://fvancop.github.io/ChartNew.js/Samples/third_bar.html but with another color for each group of rectangles (in third_bar.html they are all pink), behind the rectangles and up to the top of the chart. Correct ?

**Comment by luna2761** [comment]
> In the sample that I provided, a background rectangle appears when the mouse is hovering a rectangle
Yes, it should be kind of this, but permanently, not when the mouse hovers it.

**Comment by FVANCOP** [comment]
New sample has been added : Samples/bars_with_background_color.html.

Link for this sample : http://fvancop.github.io/ChartNew.js/Samples/bars_with_background_color.html

In this sample, 3 layouts are produced. Choose the more appropriate.

If you have other questions concerning this issue, please contact me by mail (and not through the issue) in order to avoid lot of mails generated to all the followers.

Regards,
François
