### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by jamostar** [FVANCOP/ChartNew.js#491]
Hi, 
I am having trouble making a graph to look like this: https://gyazo.com/6275ce0de9713ce6f44544013dc27311 or similar. I am given a list of names and a "startdate" and a "finishdate" for each. What is the best way to represent this, is it possible? any help would be appreciated, i have been through the documentation for many hours however i cannot for the life of me find a starting point. 

Thanks in advance

**Comment by FVANCOP** [comment]
Hi,

I first thought that it was not possible... But with little changes, I could achieve an interesting result : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/21596427/665934a8-d13b-11e6-86a1-e2cafaff1b62.png)

The changes necessary to achieve this result are not yet available in the official version (will be soon available; I still have to test it).

If you don't want to wait that this version becomes the official version, you can download the annotate.js branch at https://github.com/FVANCOP/ChartNew.js/tree/annotate.js . In this branch, the new "Samples/attendance_chart.html" produces the chart that you found here before (This branch will disappear in a couple of day).

In the code of the sample, you can change several parameters : 

- set variable labelsIteration to 1 if you want to see all dates;
- set backgroundColorWeek and backgroundColorWeekend to the same value if you don't want a different color for week and weekend days;
- startDate is the first date of the chart (in the sample : 1 January 2017);

See also the options if you prefer to have the date on the top of the chart (but in that case, you can not rotate the labels to 45 degrees).

**Comment by FVANCOP** [comment]
The branch has been merged; So you have now to download the official version !
