### ISSUE TITLE
The display of HorizontalBars is broken.

### ISSUE THREAD

**Issue by mrg21** [FVANCOP/ChartNew.js#495]
The display of HorizontalBar is broken in the current version. The bar labels are not displayed on the height of the corresponding bars:
![chrome_2017-01-23_13-32-37](https://cloud.githubusercontent.com/assets/22195317/22204343/c72ca9fe-e171-11e6-99d2-a8fdedc9b0b5.png)

**Comment by FVANCOP** [comment]
Hi,

Thanks for reporting the problem. It has been fixed just now in the available version.

Regards,
François

**Comment by mrg21** [comment]
Unfortunately, it still seems a little too far down.
![Image](http://i66.tinypic.com/raw845.png)

**Comment by FVANCOP** [comment]
Hi,

When the font size is changed, it was not correct. The last version is now correct (I hope so).

@mrg21 :  Thanks you for reporting the problem and for the feedback. 

Regards,
François

**Comment by mrg21** [comment]
Perfect, thank you.
