### ISSUE TITLE
StackedHorizontalBar and label length?

### ISSUE THREAD

**Issue by mrg21** [FVANCOP/ChartNew.js#499]
Is there a reason why longer labels generate so much free space on the right?
![image](http://img03.imgland.net/q5Df1Wd.png)

**Comment by FVANCOP** [comment]
The problem has been located but I found also other problems...

It will take some days before I publish a new version.

Thanks for reporting the problem,
François

**Comment by FVANCOP** [comment]
A new version with a fix for this problem has been published.

@mrg21 : can you test if it fixes the problem ?

**Comment by mrg21** [comment]
The new version works very well, thank you.
