### ISSUE TITLE
Legend - remove series

### ISSUE THREAD

**Issue by AK1979** [FVANCOP/ChartNew.js#506]
Hi,

Is it possible to add to data series removal from the chart legend as seen in the following example- left chart / blue ?

 
![image](https://cloud.githubusercontent.com/assets/11633641/23624514/a05c63b0-02ae-11e7-8f93-d5557c295e18.png)

Thanks !

**Comment by AK1979** [comment]
By the way, all of the recent changes to this project is amazing, thanks for all of the features !

**Comment by AK1979** [comment]
Hi
I’m not talking about null data set.
Is it possible when the legend series is clicked ( In the example -> blue ) that the chart will be updated accordingly ? ( the series would be excluded from the chart)

**Comment by FVANCOP** [comment]
Sorry, I did not understand.

Download the last version (small changes to ChartNew.js) and check Samples\issue_0506_v1.html and Samples\issue_0506_v2.html.

**Comment by AK1979** [comment]
Thanks!

I thing it would be better and less confusing that after the legend text is pressed the text will be marked as delete ( middle line ) 
as showen above ( Blue) .

**Comment by FVANCOP** [comment]
Unfortunately, strikethrough text does not exist in canvas; I have updated the ChartNew.js code and the two samples. In this new version, fill colors, legend text color, legend text style and the legend box borders can have a different values when the associated data is hidden.

**Comment by FVANCOP** [comment]
http://fvancop.github.io/ChartNew.js/Samples/issue_0506_v1.html
http://fvancop.github.io/ChartNew.js/Samples/issue_0506_v2.html

**Comment by AK1979** [comment]
Hi

I'm trying to use this option in bar chart.

In FUNC displayText the 'other' parameter == undefined and the function exits.

Any solution ? 


Thanks,
Arie.

**Comment by FVANCOP** [comment]
I just took the two Pie samples (with some changes in the data) and sets charts as Bar, HorizontalBar, StakedBar, HorizontalStackedBar and Lines : no problem with it...

http://fvancop.github.io/ChartNew.js/Samples/issue_0506_v3.html
http://fvancop.github.io/ChartNew.js/Samples/issue_0506_v4.html

Both samples have been integrated in the Samples folder.
