### ISSUE TITLE
showSingleLegend typo in documentation

### ISSUE THREAD

**Issue by ggywebtech** [FVANCOP/ChartNew.js#512]
Hi,
I have been having a few issues with this and found that there is a typo in the doc.
https://github.com/FVANCOP/ChartNew.js/wiki/100_090_Legend#showsinglelegend

Sample: showSingleValue : true
should be
Sample: showSingleLegend : true

Regards

**Comment by FVANCOP** [comment]
Fixed ! Thanks for reporting.
