### ISSUE TITLE
Drill-down with different chart types and fetch drill-down data on demand

### ISSUE THREAD

**Issue by NevillePHolistics** [FVANCOP/ChartNew.js#523]
Is it possible to drill-down from e.g. a bar graph to a pie chart? 

As a second part of this question, can the drill-down data be fetched via a function instead of being pre-populated? This because I only want to read the database for the drill-down data if necessary.

**Comment by markosko** [comment]
for different charts can't answer but for datas u can fetch them with ajax,rewrite dataobject and update chart with implemented function :)
