### ISSUE TITLE
Pie chart created but only partially rendered

### ISSUE THREAD

**Issue by NevillePerkins** [FVANCOP/ChartNew.js#525]
![image](https://user-images.githubusercontent.com/8456416/32601223-9c374de0-c54a-11e7-8d81-ed3426f75016.png)

So I have a responsive pie chart, testing here for mobile specifically. I can see that the chart is created as the title and legend is visible. When I tap on a slice of the pie chart, it even displays the annotation values. 

Why is the actual pie not visible? This seems to happen only on this chart which is the second chart on the page. On initial load, a bar graph is shown, then when you click on a bar, I hide that graph, fetch detailed data for the selected bar data point and then populate and display the pie chart. Sometimes the pie chart renders fully, sometimes not.

**Comment by FVANCOP** [comment]
Hi,

Can you send me the code (to my email address - you will find my email address in the code of ChartNew.js). What is the device / OS /browser (+version) ?

Regards,
François

**Comment by NevillePHolistics** [comment]
Hi Francois, sorry but getting you the code sample at the time was a bit too much effort as it was too embedded into the rest of my AngularJS app. In the end it had something to do with the way I was passing values from AngularJS and I managed to sort it out. You can close this issue, thanks.
