### ISSUE TITLE
angleShowLineOut on Polar Chart

### ISSUE THREAD

**Issue by DonaTanya** [FVANCOP/ChartNew.js#528]
Hello,

With Chart.js I managed to get this chart:

![image](https://user-images.githubusercontent.com/30059152/34983580-5796c2e4-faae-11e7-9163-5478ed2c57de.png)

Due to options totalAmplitude and startAngle, I realized how great this improvement is. However, I would like to have angleShowLineOut on Polar chart as well.

This is how my current chart with ChartNew.js looks like:
![image](https://user-images.githubusercontent.com/30059152/34983723-b919866e-faae-11e7-8e6d-abd357b155d8.png)

How would I implement that in the existing ChartNew.js code?

**Comment by FVANCOP** [comment]
Hi DonaTanya,

Thanks for using ChartNew.js (and sorry for the late answer).

Option angleShowLineOut has been added in the new published version. Can you download the last version and try it the new option ?

Regards,
François

PS : default value is false; you have to set option angleShowLineOut to true .

**Comment by DonaTanya** [comment]
Hi François,

Yes, this is working perfectly:

![image](https://user-images.githubusercontent.com/30059152/35209392-007669c0-ff4e-11e7-8117-9c22a906a87d.png)

Thank you very much :)
