### ISSUE TITLE
Function for annotateDisplay

### ISSUE THREAD

**Issue by meersonv** [FVANCOP/ChartNew.js#530]
After upgrade ChartNew.js to the latest version, I have problem with usage of function for annotateDisplay (as explained at issue 243).
I write:
   **annotateDisplay : setAnnotateFun**

and define function that returns "true" always (for test only):
**function setAnnotateFun (area, ctx, data, statData, posi, posj, othervars) {
    return (true);
}**

The annotation doesn't appear in Chrome and Firefox (last desktop versions), but appears in IE11

**Comment by FVANCOP** [comment]
Hi Meersonv,

You are right; it doesn't work in the last version (and probably since a long time). Problem has been fixed; Download the last version published some minutes ago.

Thanks for reporting the problem,
François

**Comment by meersonv** [comment]
Thanks a lot for quick update.
