### ISSUE TITLE
Conflict with Chart js 

### ISSUE THREAD

**Issue by shaharyar-shamshi** [FVANCOP/ChartNew.js#537]
If someone is using Chart js and new chart js simultaneously then they might face an issue because both register the function at the window. so I have fixed the issue but the major problem is it is not backward compatible Do let me know if I can open pull request with new version

**Comment by markosko** [comment]
At time of split it was drop in replacement, not sure if people used at same time Chart.js made refactoring so some things are different now, depends on FVANCOP if he take care of this repo still

**Comment by shaharyar-shamshi** [comment]
I faced the issue today so I forked the repo and changes

**Comment by shaharyar-shamshi** [comment]
@markosko I think FVANCOP is not maintaining the repo now

**Comment by FVANCOP** [comment]
Hi,

Indeed - Nothing performed in this project for a long time (because no more requests).

Francois

**Comment by shaharyar-shamshi** [comment]
![Screenshot 2021-03-26 at 2 43 22 PM](https://user-images.githubusercontent.com/17377195/112609731-e622f080-8e41-11eb-8bb5-f4450cbcfc7c.png)
Hello @FVANCOP thanks for your reply can you kindly help me how to plot this type of graph . Any prexisting example or any documentation would help me lot

**Comment by FVANCOP** [comment]
Hi,

I can reach something very similar but need a couple of days to make it more correct.

François

**Comment by shaharyar-shamshi** [comment]
Thanks a lot @FVANCOP it would great help for me if you can help me out

**Comment by FVANCOP** [comment]
![request](https://user-images.githubusercontent.com/6121933/112728170-31aeca80-8f26-11eb-9d21-56dd07546590.png)

See new file samples\issue_537.html

If you have questions about the program (or things you want to change and you don't know how to do), please contact me directly by mail (not via the "github"). Purpose is to not overload people with messages :-)
