### ISSUE TITLE
Workaround to create a new chart

### ISSUE THREAD

**Issue by JeremDsgn** [FVANCOP/ChartNew.js#60]
Hi! (once again)

I am creating a little Chrome extension, I needed to make a 'unsafe-eval' due to the `new Chart()` syntax to create the chart. There is any other way to create the chart without write `new Chart()` even if I need to write a bit more code?

Thanks.

**Comment by FVANCOP** [comment]
use fonction updateChart to update the chart.


Documentation for updateChart : https://github.com/FVANCOP/ChartNew.js/wiki/180_Update_Chart
