### ISSUE TITLE
Avoid cut off numbers

### ISSUE THREAD

**Issue by JeremDsgn** [FVANCOP/ChartNew.js#70]
There is often the last number of my chart who is cut off. One possibility to avoid this, is to add a `graphSpaceAfter`. But when my last number is egal to 0 (for instance), there is so much lost space.

![capture decran 2014-06-22 a 10 49 33](https://cloud.githubusercontent.com/assets/937328/3350984/2c4835aa-f9ea-11e3-9fb6-ce86381a6f87.png)

So, there is a way to change the text-align of the last number of the graph, to change to text-align right and avoid this cutting number.

**Comment by bhavyamanasa** [comment]
I am also with same problem.. i have one chart which displays the month wise results but last month value is not displaying full. 
if i specified the value for inGraphDataAlign: "left", as "right" then the left side values are overlapping


before
![pic1](https://cloud.githubusercontent.com/assets/11133804/6328775/d9317ba6-bb90-11e4-9fd0-93ebe81ecff7.png)


after
![pic2](https://cloud.githubusercontent.com/assets/11133804/6328889/cb6ab86a-bb91-11e4-8960-75727bd92925.png)

**Comment by FVANCOP** [comment]
@bhavyamanasa - I don't know why your message received by mail is not reffered here... but perhaps a solution to this - really not simple - problem : since the last version (see https://github.com/FVANCOP/ChartNew.js/wiki/130_option_functions), with a function, you can change the position for the last "inGraphData".

Example : 

     var setPosInGraphData = function (area, ctx, data, statData, posi, posj, othervars) {
	     if (area=="INGRAPHDATAALIGN") {
		     if(posj==data.datasets[posi].data.length-1)return("right");
		     else return("left");
	     } else if (area=="INGRAPHDATAVALIGN") {
		     if(posj==data.datasets[posi].data.length-1)return("top");
		     else	return("bottom");
	     } else if (area=="INGRAPHDATAPADDINGX") {
		     if(posj==data.datasets[posi].data.length-1)return(-3);
		     else	return(3);
	     } else if (area=="INGRAPHDATAPADDINGY") {
		     if(posj==data.datasets[posi].data.length-1)return(-3);
		     else	return(3);
	     }
     }

and set following options :  

      inGraphDataAlign : setPosInGraphData
      inGraphDataVAlign : setPosInGraphData
      inGraphDataPaddingX: setPosInGraphData
      inGraphDataPaddingY: setPosInGraphData
