### ISSUE TITLE
Line Graph: Round Y axis to whole number or force scaleStepWidth => 1.

### ISSUE THREAD

**Issue by Antman261** [FVANCOP/ChartNew.js#76]
I'd like to leave scaleOverride set to false, except it shouldn't show decimal places in some circumstances, but does with low values. This doesn't make sense when you're displaying something that cannot be less than whole.

There currently isn't an easy way to do this (that I've found) without turning on scaleOverride.

**Comment by theBear** [comment]
BUT if you also set graphMax (e.g.) to "100" and in combination with yAxisMinimumInterval = 1 the "100" won't be shown sometimes. It depends on the width, but I think it's better to show ALWAYS the max height in the y-axis. Take a look at this chart with "98":

![yaxisminimuminterval](https://cloud.githubusercontent.com/assets/7254827/6059129/73632d30-ad2e-11e4-8544-64db0f7369a6.png)

If I enlarge this a bit, it becomes "100":

![yaxisminimuminterval2](https://cloud.githubusercontent.com/assets/7254827/6059139/88f7ccd2-ad2e-11e4-8034-918ff4194158.png)

**Comment by FVANCOP** [comment]
Hi @theBear  ! 

Thanks for reporting this bug ! It has been fixed (I hope so). Download the last version to get it solved or contact me back if not....

Francois

**Comment by theBear** [comment]
Thank you very much! I will take a look and will report if there are any issues left concerning this.

**Comment by mtangoo** [comment]
Thank you for this fix. I believe it deserve a mention on docs.
Otherwise thanks for great library!
