### ISSUE TITLE
Rendering chart on retina is blurry - Horizontal Bar Chart

### ISSUE THREAD

**Issue by Atbhatt** [FVANCOP/ChartNew.js#85]
The graph does not appear to be optimized for retina displays. 

![screen shot 2014-07-09 at 11 07 53 am](https://cloud.githubusercontent.com/assets/1020047/3528914/f95455d6-0793-11e4-9c70-2df0f8773b36.png)

Any help with getting this to render clear on retina would be greatly appreciated!

Thank you!

**Comment by nitinhayaran** [comment]
Looks like this issue still exists. Have you found a fix for this?

**Comment by FVANCOP** [comment]
A new version has been published today. I hope that it fixes this issue.

**Comment by nitinhayaran** [comment]
I am afraid to say, that issue still exists. I have tested it on the demo site.

**Comment by FVANCOP** [comment]
@nitinhayaran : Sorry, but ChartNew.js module on the demo site was not up-to-date. It is now the case. Can you retry ?

**Comment by nitinhayaran** [comment]
@FVANCOP Cool, it works. 
Thanks for this, now I can replace Chart.js peacefully.
